// Spoonmap - Today Dessert 134 Restaurants Dataset
const TODAY_DESSERT_FRIEND_DATA = {
  "id": "friend_todaydessert",
  "name": "투데이디저트",
  "nickname": "투데이디저트",
  "avatarText": "디",
  "avatarEmoji": "🍰",
  "color": "#DB2777",
  "comment": "100% 숏츠 기반! 전국 방방곡곡 숨겨진 찐 디저트 & 베이커리 핫플 (134곳)",
  "restaurants": [
    {
      "name": "비캔드",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 망원동 485-13",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 10회 추천 디저트 핫플!\n• [영상 1: 서울 복숭아 디저트 모음집]\n• [영상 2: 복숭아가 통으로 올라간 프렌치토스트] → 망원동 브런치 카페 <비캔드>에서 시즌 한정으로 선보이는 복숭아 프렌치토스트. 노릇하게 구운 수제 브리오슈 위에 복숭아 과육이 통째로 올라간 비...\n• [영상 3: 억지 유행이라는 우베 디저트 근황] - 우베크림브륄레 프렌치토스트\n• [영상 4: 억지유행이라는 우베..?] - 우베 브륄레 프렌치토스트\n• [영상 5: 2026 딸기 디저트 모음집] - 딸기 프렌치토스트\n• [영상 6: 복숭아 디저트 먹고 싶을 때 보면 좋은 영상]\n• [영상 7: 복숭아 하나가 통째로 올라간다고..?]\n• [영상 8: 서울 초당옥수수 디저트 모음집] - 초당옥수수 프렌치토스트\n• [영상 9: 쏟아지는 프렌치토스트]\n• [영상 10: 말차 초코 프렌치토스트] - 망원동",
      "x": "126.90737673573257",
      "y": "37.557223020178924",
      "map_url": "https://map.kakao.com/link/search/%EB%B9%84%EC%BA%94%EB%93%9C",
      "kakao_url": "https://place.map.kakao.com/1443924309",
      "youtube_url": "https://www.youtube.com/shorts/2gFTzHD37xA",
      "youtube_title": "서울 복숭아 디저트 모음집",
      "video_count": 10,
      "menu": [
        "우베크림브륄레 프렌치토스트",
        "우베 브륄레 프렌치토스트",
        "딸기 프렌치토스트",
        "초당옥수수 프렌치토스트",
        "망원동"
      ]
    },
    {
      "name": "토터스",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 용산동2가 18-3",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 6회 추천 디저트 핫플!\n• [영상 1: 서울 복숭아 디저트 모음집]\n• [영상 2: 2026 딸기 디저트 모음집] - 딸기 모찌 수플레\n• [영상 3: 디저트에 미친 사람의 2025년은 어땠을까..?] - 말차 모찌수플레\n• [영상 4: 쫄깃한 말차 모찌 수플레]\n• [영상 5: 복숭아처럼 생긴 수플레]\n• [영상 6: 방수 코팅 수플레]",
      "x": "126.9860815598319",
      "y": "37.545322104940205",
      "map_url": "https://map.kakao.com/link/search/%ED%86%A0%ED%84%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/1968574408",
      "youtube_url": "https://www.youtube.com/shorts/2gFTzHD37xA",
      "youtube_title": "서울 복숭아 디저트 모음집",
      "video_count": 6,
      "menu": [
        "딸기 모찌 수플레",
        "말차 모찌수플레"
      ]
    },
    {
      "name": "푸드떼",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 사간동 26",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 6회 추천 디저트 핫플!\n• [영상 1: 지금 놓치면 1년을 기다려야 하는 무화과 파르페] → 한옥 공간에서 계절마다 파르페를 선보이는 <푸드떼>. 이번 시즌은 카시스 무화과 몽블랑 파르페였다. 진한 카시스 풍미와 제철 무화과가 어우러져 ...\n• [영상 2: 서울 복숭아 디저트 모음집]\n• [영상 3: 복숭아 하나가 통으로 올라가는 파르페] → 안국역 골목에 위치한 티 전문점 <푸드떼>. 이번 여름에는 복숭아 하나가 통으로 올라간 시즌 파르페를 선보인다. 복숭아 과육 상태가 정말 좋았고...\n• [영상 4: 디저트에 미친 사람의 2025년은 어땠을까..?] - 말차 파르페\n• [영상 5: 화가 나는 무화과 파르페]\n• [영상 6: 복숭아 디저트 먹고 싶을 때 보면 좋은 영상]",
      "x": "126.98136605296132",
      "y": "37.57798078276651",
      "map_url": "https://map.kakao.com/link/search/%ED%91%B8%EB%93%9C%EB%96%BC",
      "kakao_url": "https://place.map.kakao.com/763707742",
      "youtube_url": "https://www.youtube.com/shorts/5YCjgvyYcas",
      "youtube_title": "지금 놓치면 1년을 기다려야 하는 무화과 파르페",
      "video_count": 6,
      "menu": [
        "말차 파르페"
      ]
    },
    {
      "name": "라프레플루트",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 685-495",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 5회 추천 디저트 핫플!\n• [영상 1: 서울 복숭아 디저트 모음집]\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 말차 딸기케이크\n• [영상 3: 복숭아 디저트 먹고 싶을 때 보면 좋은 영상]\n• [영상 4: 서울 초당옥수수 디저트 모음집] - 초당옥수수 아이스크림\n• [영상 5: 멜론 디저트 한상차림]",
      "x": "127.03943885948081",
      "y": "37.54725168493599",
      "map_url": "https://map.kakao.com/link/search/%EB%9D%BC%ED%94%84%EB%A0%88%ED%94%8C%EB%A3%A8%ED%8A%B8",
      "kakao_url": "https://place.map.kakao.com/519985882",
      "youtube_url": "https://www.youtube.com/shorts/2gFTzHD37xA",
      "youtube_title": "서울 복숭아 디저트 모음집",
      "video_count": 5,
      "menu": [
        "말차 딸기케이크",
        "초당옥수수 아이스크림"
      ]
    },
    {
      "name": "미엘케이커리",
      "category": "☕카페",
      "location_large": "서울 관악구",
      "road_address": "서울 관악구 봉천동 1612-40 3층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 5회 추천 디저트 핫플!\n• [영상 1: 빙수 위에 지금 뭘 올리시는거죠..?] - 푸딩빙수\n• [영상 2: 억지 유행이라는 우베 디저트 근황] - 우베 갸또\n• [영상 3: 우베가 무슨 맛인지 모르겠다고요..?] - 미엘케이커리\n• [영상 4: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이쫀득대창\n• [영상 5: 네..? '두바이 쫀득 통대창'이요..?] - 두바이 쫀득 통대창",
      "x": "126.9565589285869",
      "y": "37.478446003805985",
      "map_url": "https://map.kakao.com/link/search/%EB%AF%B8%EC%97%98%EC%BC%80%EC%9D%B4%EC%BB%A4%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/1795448015",
      "youtube_url": "https://www.youtube.com/shorts/mGQPV2jl1IA",
      "youtube_title": "빙수 위에 지금 뭘 올리시는거죠..?",
      "video_count": 5,
      "menu": [
        "푸딩빙수",
        "우베 갸또",
        "미엘케이커리",
        "두바이쫀득대창",
        "두바이 쫀득 통대창"
      ]
    },
    {
      "name": "이미커피",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 동교동 201-10",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 4회 추천 디저트 핫플!\n• [영상 1: 서울 복숭아 디저트 모음집]\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 통복숭아 타르트\n• [영상 3: 복숭아 디저트 먹고 싶을 때 보면 좋은 영상]\n• [영상 4: 복숭아 디저트에 진심이라면..]",
      "x": "126.92192185384238",
      "y": "37.557475001772985",
      "map_url": "https://map.kakao.com/link/search/%EC%9D%B4%EB%AF%B8%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/15985522",
      "youtube_url": "https://www.youtube.com/shorts/2gFTzHD37xA",
      "youtube_title": "서울 복숭아 디저트 모음집",
      "video_count": 4,
      "menu": [
        "통복숭아 타르트"
      ]
    },
    {
      "name": "파티스리 까이에",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 월드컵로3길 14 딜라이트 스퀘어 2차 상가동 1층 105호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 4회 추천 디저트 핫플!\n• [영상 1: 서울 파티세리 모음집]\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 바닐라 타르트\n• [영상 3: 무화과 쑥 케이크]\n• [영상 4: 최고의 바닐라 타르트]",
      "x": "126.9123366001328",
      "y": "37.551006319629764",
      "map_url": "https://map.kakao.com/link/search/%ED%8C%8C%ED%8B%B0%EC%8A%A4%EB%A6%AC%20%EA%B9%8C%EC%9D%B4%EC%97%90",
      "kakao_url": "https://place.map.kakao.com/1896030091",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 4,
      "menu": [
        "바닐라 타르트"
      ]
    },
    {
      "name": "기댈빙",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 685-414",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 서울 빙수 모음집]\n• [영상 2: 성수동 망고스틴빙수] → 서울숲에 위치한 빙수 전문점 <기댈빙>. 우유얼음 위에 뽀얀 생망고스틴이 빈틈없이 뒤덮여 있는데, 비주얼이 언뜻 통마늘을 쌓아 올린 것 같아 독...\n• [영상 3: 평양냉면이 아니라 평양빙수..?]",
      "x": "127.04103645288036",
      "y": "37.546815057082505",
      "map_url": "https://map.kakao.com/link/search/%EA%B8%B0%EB%8C%88%EB%B9%99",
      "kakao_url": "https://place.map.kakao.com/332229378",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 3,
      "menu": []
    },
    {
      "name": "라프레플루트",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 서울숲2길 8-8 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 성수동 4단 무화과케이크] - 무화과 크레이프 케이크 → 성수동 서울숲에 위치한 과일 디저트 전문점 <라프레플루트>. 무화과 시즌을 맞아 선보인 '무화과 크레이프 케이크'를 맛보고 왔다. 쑥 크레이프 ...\n• [영상 2: 복숭아 지분 80%인 케이크..?]\n• [영상 3: 말차 체리 케이크] - 말차체리케이크",
      "x": "127.03943885948081",
      "y": "37.54725168493599",
      "map_url": "https://map.kakao.com/link/search/%EB%9D%BC%ED%94%84%EB%A0%88%ED%94%8C%EB%A3%A8%ED%8A%B8",
      "kakao_url": "https://place.map.kakao.com/519985882",
      "youtube_url": "https://www.youtube.com/shorts/IgXdHhhYpPE",
      "youtube_title": "성수동 4단 무화과케이크",
      "video_count": 3,
      "menu": [
        "무화과 크레이프 케이크",
        "말차체리케이크"
      ]
    },
    {
      "name": "썸띵어바웃커피",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 역삼동 618-16",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 2026 서울 치즈케이크 모음집..!] - 호두정과 치즈케이크\n• [영상 2: 이게 바로 K-치즈케이크..?] → 고소한 호두 치즈케이크 위에 곶감 크림을 올리고, 잣과 바삭한 호두정과를 듬뿍 얹은 구성. 호두의 묵직한 고소함과 곶감의 은은한 단맛, 씹히는 ...\n• [영상 3: 서울 초당옥수수 디저트 모음집] - 초당옥수수 치즈케이크 빙수",
      "x": "127.02779847587531",
      "y": "37.502824775159816",
      "map_url": "https://map.kakao.com/link/search/%EC%8D%B8%EB%9D%B5%EC%96%B4%EB%B0%94%EC%9B%83%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/2005375589",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 3,
      "menu": [
        "호두정과 치즈케이크",
        "초당옥수수 치즈케이크 빙수"
      ]
    },
    {
      "name": "우나스",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 영동대로118길 56 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 서울 파티세리 모음집]\n• [영상 2: 강남에서 이런 디저트는 처음 봅니다..?] - 우나스(UNAS)\n• [영상 3: 역대급으로 귀여운 크리스마스 케이크]",
      "x": "127.0627977260317",
      "y": "37.5177824435977",
      "map_url": "https://map.kakao.com/link/search/%EC%9A%B0%EB%82%98%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/1900672501",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 3,
      "menu": [
        "우나스(UNAS)"
      ]
    },
    {
      "name": "진켈란젤로",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 합정동 362-5",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 2026 서울 치즈케이크 모음집..!] - 트러플 치즈케이크\n• [영상 2: 역대급 부드러운 치즈케이크] - 블루치즈 바스크 → 합정동에 위치한 치즈케이크 전문점 <진켈란젤로>. 블루치즈, 메이플, 말차, 트러플 등 다채로운 라인업의 바스크 치즈케이크를 선보이는 곳이다. ...\n• [영상 3: 디저트에 미친 사람의 2025년은 어땠을까..?] - 바스크치즈케이크",
      "x": "126.91798518463615",
      "y": "37.54750729657302",
      "map_url": "https://map.kakao.com/link/search/%EC%A7%84%EC%BC%88%EB%9E%80%EC%A0%A4%EB%A1%9C",
      "kakao_url": "https://place.map.kakao.com/220436672",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 3,
      "menu": [
        "트러플 치즈케이크",
        "블루치즈 바스크",
        "바스크치즈케이크"
      ]
    },
    {
      "name": "차일디쉬",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동2가 275-12",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 서울 빙수 모음집]\n• [영상 2: 억지 유행이라는 우베 디저트 근황] - 우베 빙수\n• [영상 3: 붕어팡 틀에 소금빵을 구우면?]",
      "x": "127.06159472156686",
      "y": "37.540470295750424",
      "map_url": "https://map.kakao.com/link/search/%EC%B0%A8%EC%9D%BC%EB%94%94%EC%89%AC",
      "kakao_url": "https://place.map.kakao.com/2009228453",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 3,
      "menu": [
        "우베 빙수"
      ]
    },
    {
      "name": "크레몽",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 논현동 278-14",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 2026 서울 치즈케이크 모음집..!] - 우베 바스크 치즈케이크\n• [영상 2: 억지 유행이라는 우베 디저트 근황] - 우베 바스크치즈케이크\n• [영상 3: 말차 다음 유행은 이거..?] - 우베 → 요즘 말차 다음으로 디저트계에서 새롭게 떠오르는 식재료 '우베'. 서울에서 우베로 만든 바스크 치즈케이크를 선보이는 곳이 있어 발 빠르게 다녀왔...",
      "x": "127.04247325788079",
      "y": "37.51031677244347",
      "map_url": "https://map.kakao.com/link/search/%ED%81%AC%EB%A0%88%EB%AA%BD",
      "kakao_url": "https://place.map.kakao.com/739795519",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 3,
      "menu": [
        "우베 바스크 치즈케이크",
        "우베 바스크치즈케이크",
        "우베"
      ]
    },
    {
      "name": "키릴",
      "category": "☕카페",
      "location_large": "서울 강서구",
      "road_address": "서울 강서구 공항대로53길 23 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 3회 추천 디저트 핫플!\n• [영상 1: 서울 파티세리 모음집]\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 쑥 타르트\n• [영상 3: 섬이 올라간 쑥 타르트]",
      "x": "126.85995203684793",
      "y": "37.55450213354859",
      "map_url": "https://map.kakao.com/link/search/%ED%82%A4%EB%A6%B4",
      "kakao_url": "https://place.map.kakao.com/376693772",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 3,
      "menu": [
        "쑥 타르트"
      ]
    },
    {
      "name": "고로커피로스터스",
      "category": "☕카페",
      "location_large": "서울 관악구",
      "road_address": "서울특별시 관악구 남부순환로231길 33 (봉천동) 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 무화과, 흑임자에 진심인 케이크] → 매년 무화과 시즌마다 꾸준히 챙겨 먹는<고로커피로스터스>의 시그니처 디저트. 제철 무화과의 향긋함과 흑임자의 고소한 풍미가 조화롭게 어우러진다....\n• [영상 2: 최애 무화과 디저트] - 밤부 라떼",
      "x": "126.960241",
      "y": "37.477412",
      "map_url": "https://map.kakao.com/link/search/%EA%B3%A0%EB%A1%9C%EC%BB%A4%ED%94%BC%EB%A1%9C%EC%8A%A4%ED%84%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/508064654",
      "youtube_url": "https://www.youtube.com/shorts/yqMfUe7zsDU",
      "youtube_title": "무화과, 흑임자에 진심인 케이크",
      "video_count": 2,
      "menu": [
        "밤부 라떼"
      ]
    },
    {
      "name": "꼬내과자점",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 385-6",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 2026 서울 치즈케이크 모음집..!] - 더블바닐라 바스크 치즈케이크\n• [영상 2: 바닐라 가글 치즈케이크] → 바닐라빈을 두 배 듬뿍 넣어 구워내 중앙은 크리미하고 가장자리는 꾸덕한 식감의 바스크 치즈케이크. 한 입 먹자마자 바닐라 풍미가 엄청 진하게 치...",
      "x": "126.92608193634673",
      "y": "37.56234306203403",
      "map_url": "https://map.kakao.com/link/search/%EA%BC%AC%EB%82%B4%EA%B3%BC%EC%9E%90%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1585348190",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 2,
      "menu": [
        "더블바닐라 바스크 치즈케이크"
      ]
    },
    {
      "name": "누데이크 티 하우스",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 뚝섬로 433 5층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 요즘 MZ들은 성수동 가면 어딜 갈까?]\n• [영상 2: 성수동에서 가장 비싼 디저트는 얼마일까?]",
      "x": "127.05894067159399",
      "y": "37.53818671430299",
      "map_url": "https://map.kakao.com/link/search/%EB%88%84%EB%8D%B0%EC%9D%B4%ED%81%AC%20%ED%8B%B0%20%ED%95%98%EC%9A%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/750562735",
      "youtube_url": "https://www.youtube.com/shorts/3WbPOgfOvrA",
      "youtube_title": "요즘 MZ들은 성수동 가면 어딜 갈까?",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "디어스윗랩",
      "category": "☕카페",
      "location_large": "경기 수원시",
      "road_address": "경기 수원시 영통구 이의동 1318-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이쫀득김밥\n• [영상 2: 두바이쫀득쿠키 말고 두바이쫀득김밥..!]",
      "x": "127.05587599797354",
      "y": "37.29402291290958",
      "map_url": "https://map.kakao.com/link/search/%EB%94%94%EC%96%B4%EC%8A%A4%EC%9C%97%EB%9E%A9",
      "kakao_url": "https://place.map.kakao.com/1709156058",
      "youtube_url": "https://www.youtube.com/shorts/-SahFIs2ptU",
      "youtube_title": "하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!",
      "video_count": 2,
      "menu": [
        "두바이쫀득김밥"
      ]
    },
    {
      "name": "리브인오후",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 망원동 399-10",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 2026 서울 치즈케이크 모음집..!] - 완두콩 치즈케이크\n• [영상 2: 이걸로 만든 치즈케이크는 처음 봅니다..!] - 완두 치즈케이크 → 디저트 덕후들의 망원동 아지트 <리브인오후>. 이곳의 독보적인 시그니처 메뉴인 '완두 치즈케이크'를 맛보고 왔다. 바삭한 크럼블 시트 위에 달콤...",
      "x": "126.90418006716533",
      "y": "37.55413905849442",
      "map_url": "https://map.kakao.com/link/search/%EB%A6%AC%EB%B8%8C%EC%9D%B8%EC%98%A4%ED%9B%84",
      "kakao_url": "https://place.map.kakao.com/86103478",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 2,
      "menu": [
        "완두콩 치즈케이크",
        "완두 치즈케이크"
      ]
    },
    {
      "name": "몽슈와파티세리",
      "category": "☕카페",
      "location_large": "서울 서초구",
      "road_address": "서울 서초구 서초동 1530-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 복숭아 디저트 모음집]\n• [영상 2: 작품 같은 신비복숭아 타르트] - 신비 → 서초동에 위치한 디저트 숍 <몽슈와 파티세리>. 시즌 한정으로 신비복숭아를 활용한 타르트 '신비'를 선보인다. 타르트지 위에 신비복숭아 과육을 ...",
      "x": "127.00973288308973",
      "y": "37.48557876682161",
      "map_url": "https://map.kakao.com/link/search/%EB%AA%BD%EC%8A%88%EC%99%80%ED%8C%8C%ED%8B%B0%EC%84%B8%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/1670956155",
      "youtube_url": "https://www.youtube.com/shorts/2gFTzHD37xA",
      "youtube_title": "서울 복숭아 디저트 모음집",
      "video_count": 2,
      "menu": [
        "신비"
      ]
    },
    {
      "name": "무디브레드마켓",
      "category": "☕카페",
      "location_large": "부산 부산진구",
      "road_address": "부산 부산진구 전포동 308-16",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 디저트에 미친 사람의 2025년은 어땠을까..?] - 아라고스타\n• [영상 2: 가장 바삭한 크림빵] - 아라고스타",
      "x": "129.0668074545716",
      "y": "35.1557240973068",
      "map_url": "https://map.kakao.com/link/search/%EB%AC%B4%EB%94%94%EB%B8%8C%EB%A0%88%EB%93%9C%EB%A7%88%EC%BC%93",
      "kakao_url": "https://place.map.kakao.com/1105757340",
      "youtube_url": "https://www.youtube.com/shorts/4EUphEtgyWI",
      "youtube_title": "디저트에 미친 사람의 2025년은 어땠을까..?",
      "video_count": 2,
      "menu": [
        "아라고스타"
      ]
    },
    {
      "name": "무심",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 후암로13길 4 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 콩국수맛 아이스크림] - 콩국수 맛 아이스크림 → 용산 후암동에 위치한 디저트 카페 <무심>. 이번 여름 시즌에만 이벤트성으로 '콩국수 맛 아이스크림'을 선보인다. 진한 콩물과 콩맛 아이스크림을...\n• [영상 2: 멜론 참외 빙수와 오이아이스크림] - 멜론 참외 빙수",
      "x": "126.9776165375036",
      "y": "37.54799857270168",
      "map_url": "https://map.kakao.com/link/search/%EB%AC%B4%EC%8B%AC",
      "kakao_url": "https://place.map.kakao.com/827270380",
      "youtube_url": "https://www.youtube.com/shorts/mgr6SQiB0oQ",
      "youtube_title": "콩국수맛 아이스크림",
      "video_count": 2,
      "menu": [
        "콩국수 맛 아이스크림",
        "멜론 참외 빙수"
      ]
    },
    {
      "name": "발렁스",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 계동길 50 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 파티세리 모음집]\n• [영상 2: 안국역에서 발견한 최고의 바닐라 디저트..!] - 발렁스",
      "x": "126.98684049764644",
      "y": "37.57950239797048",
      "map_url": "https://map.kakao.com/link/search/%EB%B0%9C%EB%A0%81%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/695841671",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 2,
      "menu": [
        "발렁스"
      ]
    },
    {
      "name": "보연희",
      "category": "☕카페",
      "location_large": "서울 서대문구",
      "road_address": "서울 서대문구 연희맛로 17-63 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 무화과 피스타치오 다쿠아즈] → 올해도 어김없이 첫 무화과 디저트는 연희동 <보연희>에서 시작했다. 폭신한 다쿠아즈 시트 위에 통무화과를 큼직하게 얹고, 진한 피스타치오 크림을...\n• [영상 2: 서울 복숭아 디저트 모음집]",
      "x": "126.92877118246103",
      "y": "37.56709837022641",
      "map_url": "https://map.kakao.com/link/search/%EB%B3%B4%EC%97%B0%ED%9D%AC",
      "kakao_url": "https://place.map.kakao.com/1701450327",
      "youtube_url": "https://www.youtube.com/shorts/IO54cRjcpFA",
      "youtube_title": "무화과 피스타치오 다쿠아즈",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "브릭베이글",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 망원동 338-64",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이베이글\n• [영상 2: 망원동 두바이 베이글]",
      "x": "126.90713753065275",
      "y": "37.5529881445515",
      "map_url": "https://map.kakao.com/link/search/%EB%B8%8C%EB%A6%AD%EB%B2%A0%EC%9D%B4%EA%B8%80",
      "kakao_url": "https://place.map.kakao.com/126067252",
      "youtube_url": "https://www.youtube.com/shorts/-SahFIs2ptU",
      "youtube_title": "하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!",
      "video_count": 2,
      "menu": [
        "두바이베이글"
      ]
    },
    {
      "name": "새들러하우스",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 신사동 561-8",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 두바이쫀득쿠키 다음은 이거라고..?] - 새들러하우스\n• [영상 2: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이누드김밥",
      "x": "127.02492234849987",
      "y": "37.51938227391972",
      "map_url": "https://map.kakao.com/link/search/%EC%83%88%EB%93%A4%EB%9F%AC%ED%95%98%EC%9A%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/1341473552",
      "youtube_url": "https://www.youtube.com/shorts/hOPdjx64IgQ",
      "youtube_title": "두바이쫀득쿠키 다음은 이거라고..?",
      "video_count": 2,
      "menu": [
        "새들러하우스",
        "두바이누드김밥"
      ]
    },
    {
      "name": "슈퍼말차 성수",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 668-9",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 말차 빙수 모음집]\n• [영상 2: 성수동 말차 라떼 근황]",
      "x": "127.0437210250712",
      "y": "37.54751687270709",
      "map_url": "https://map.kakao.com/link/search/%EC%8A%88%ED%8D%BC%EB%A7%90%EC%B0%A8%20%EC%84%B1%EC%88%98",
      "kakao_url": "https://place.map.kakao.com/2077832392",
      "youtube_url": "https://www.youtube.com/shorts/mh-ixVr8MGU",
      "youtube_title": "서울 말차 빙수 모음집",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "스쿠퍼젤라또",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 자하문로7길 10 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 쑥 젤라또로 만든 아포가토]\n• [영상 2: 쑥 젤라또로 만든 아포가토]",
      "x": "126.97118628406648",
      "y": "37.578382382338795",
      "map_url": "https://map.kakao.com/link/search/%EC%8A%A4%EC%BF%A0%ED%8D%BC%EC%A0%A4%EB%9D%BC%EB%98%90",
      "kakao_url": "https://place.map.kakao.com/2142374128",
      "youtube_url": "https://www.youtube.com/shorts/zVNHWlhuR4c",
      "youtube_title": "쑥 젤라또로 만든 아포가토",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "썸머러너",
      "category": "☕카페",
      "location_large": "서울 강동구",
      "road_address": "서울 강동구 천호대로 989 1층 102호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 힙업 운동 한 뚱이 보러 가실 분..?] - 뚱이 → 천호동에 위치한 디저트 카페 <썸머러너>. 스폰지밥의 '뚱이' 뒤태를 리얼하게 재현한 이색 푸딩을 선보인다. 바닐라 크림 푸딩을 중심으로 상큼한...\n• [영상 2: 메타몽 푸딩 Ditto Pudding]",
      "x": "127.12239570791174",
      "y": "37.53945345420828",
      "map_url": "https://map.kakao.com/link/search/%EC%8D%B8%EB%A8%B8%EB%9F%AC%EB%84%88",
      "kakao_url": "https://place.map.kakao.com/992839775",
      "youtube_url": "https://www.youtube.com/shorts/T_pGyEZ8ukY",
      "youtube_title": "힙업 운동 한 뚱이 보러 가실 분..?",
      "video_count": 2,
      "menu": [
        "뚱이"
      ]
    },
    {
      "name": "엔엘커피",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 합정동 441-4",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 디저트에 미친 사람의 2025년은 어땠을까..?] - 말차케이크\n• [영상 2: 난생 처음 보는 말차 디저트]",
      "x": "126.90561761442267",
      "y": "37.55212918952413",
      "map_url": "https://map.kakao.com/link/search/%EC%97%94%EC%97%98%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/1146130981",
      "youtube_url": "https://www.youtube.com/shorts/4EUphEtgyWI",
      "youtube_title": "디저트에 미친 사람의 2025년은 어땠을까..?",
      "video_count": 2,
      "menu": [
        "말차케이크"
      ]
    },
    {
      "name": "웨스턴챕터",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 685-498",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 성수동에서 케이크를 주문하면 생기는 일]\n• [영상 2: 두바이 치즈케이크 - Dubai Chocolate Cheesecake] - 두바이 치즈케이크",
      "x": "127.03972850558227",
      "y": "37.5471650919502",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%A8%EC%8A%A4%ED%84%B4%EC%B1%95%ED%84%B0",
      "kakao_url": "https://place.map.kakao.com/656677493",
      "youtube_url": "https://www.youtube.com/shorts/qHcHKB8Keu8",
      "youtube_title": "성수동에서 케이크를 주문하면 생기는 일",
      "video_count": 2,
      "menu": [
        "두바이 치즈케이크"
      ]
    },
    {
      "name": "웨스틴 서울 파르나스",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 삼성동 159",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 빙수 모음집]\n• [영상 2: 5성급 호텔에서 빙수를 주문하면 생기는 일] - 웨스틴 서울 파르나스",
      "x": "127.05728738514722",
      "y": "37.512768456315044",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%A8%EC%8A%A4%ED%8B%B4%20%EC%84%9C%EC%9A%B8%20%ED%8C%8C%EB%A5%B4%EB%82%98%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/89757736",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 2,
      "menu": [
        "웨스틴 서울 파르나스"
      ]
    },
    {
      "name": "윤숲 후르츠산도점",
      "category": "☕카페",
      "location_large": "서울 광진구",
      "road_address": "서울 광진구 중곡동 628-7",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이산도\n• [영상 2: 과연 두바이산도는 얼마일까?]",
      "x": "127.07727447078621",
      "y": "37.55954782351352",
      "map_url": "https://map.kakao.com/link/search/%EC%9C%A4%EC%88%B2%20%ED%9B%84%EB%A5%B4%EC%B8%A0%EC%82%B0%EB%8F%84%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1775568752",
      "youtube_url": "https://www.youtube.com/shorts/-SahFIs2ptU",
      "youtube_title": "하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!",
      "video_count": 2,
      "menu": [
        "두바이산도"
      ]
    },
    {
      "name": "을지로문덕커피",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 저동2가 6-3",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 빙수 모음집]\n• [영상 2: 아는 사람들만 아는 맛도리 빙수]",
      "x": "126.99016622087849",
      "y": "37.5651696924836",
      "map_url": "https://map.kakao.com/link/search/%EC%9D%84%EC%A7%80%EB%A1%9C%EB%AC%B8%EB%8D%95%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/1818118278",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "정애쿠키",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 227-16",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 10년 넘게 쿠키를 만드신 할머니를 아시나요..?] - 정애쿠키\n• [영상 2: 쿠키가 하나에 800원..?] - 고추쿠키",
      "x": "126.92656640501166",
      "y": "37.56230011652859",
      "map_url": "https://map.kakao.com/link/search/%EC%A0%95%EC%95%A0%EC%BF%A0%ED%82%A4",
      "kakao_url": "https://place.map.kakao.com/25537173",
      "youtube_url": "https://www.youtube.com/shorts/47WGce-Iz_Q",
      "youtube_title": "10년 넘게 쿠키를 만드신 할머니를 아시나요..?",
      "video_count": 2,
      "menu": [
        "정애쿠키",
        "고추쿠키"
      ]
    },
    {
      "name": "조앤도슨",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 254-8",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 인생 프렌치토스트집을 아시나요..?] → 연남동에서 단 하나의 메뉴만으로 오랜 시간 사랑받고 있는 프렌치토스트 성지 <조앤도슨>. 겉은 노릇하게 구워 바삭하고, 속은 계란과 버터 풍미가...\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 프렌치토스트",
      "x": "126.92319667663513",
      "y": "37.56364586299234",
      "map_url": "https://map.kakao.com/link/search/%EC%A1%B0%EC%95%A4%EB%8F%84%EC%8A%A8",
      "kakao_url": "https://place.map.kakao.com/43859487",
      "youtube_url": "https://www.youtube.com/shorts/Q4mTunViRy8",
      "youtube_title": "서울 인생 프렌치토스트집을 아시나요..?",
      "video_count": 2,
      "menu": [
        "프렌치토스트"
      ]
    },
    {
      "name": "지엠엘 도산",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 신사동 647-8",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 디저트에 미친 사람의 2025년은 어땠을까..?] - 초코 뺑오쇼콜라\n• [영상 2: 뭐어..? 초코빵이 하나에 8800원..?]",
      "x": "127.03651758542976",
      "y": "37.52516009123201",
      "map_url": "https://map.kakao.com/link/search/%EC%A7%80%EC%97%A0%EC%97%98%20%EB%8F%84%EC%82%B0",
      "kakao_url": "https://place.map.kakao.com/325284241",
      "youtube_url": "https://www.youtube.com/shorts/4EUphEtgyWI",
      "youtube_title": "디저트에 미친 사람의 2025년은 어땠을까..?",
      "video_count": 2,
      "menu": [
        "초코 뺑오쇼콜라"
      ]
    },
    {
      "name": "카페포모",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 논현동 256",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 억지 유행이라는 우베 디저트 근황] - 우베 크레이프롤\n• [영상 2: 이런 우베 디저트는 처음입니다..] - 카페포모",
      "x": "127.03903632325648",
      "y": "37.51312548760199",
      "map_url": "https://map.kakao.com/link/search/%EC%B9%B4%ED%8E%98%ED%8F%AC%EB%AA%A8",
      "kakao_url": "https://place.map.kakao.com/408042677",
      "youtube_url": "https://www.youtube.com/shorts/0Frib43pNNk",
      "youtube_title": "억지 유행이라는 우베 디저트 근황",
      "video_count": 2,
      "menu": [
        "우베 크레이프롤",
        "카페포모"
      ]
    },
    {
      "name": "코리야",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 656-640",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 빙수 모음집]\n• [영상 2: 72시간 동안 얼린 얼음으로 만든 빙수] - 코리야 → 성수동에 위치한 빙수 전문점 '코리야'. 이곳은 특이하게 72시간 동안 얼린 얼음을 갈아서 빙수를 만든다. 대표 메뉴 중 하나인 흑임자빙수를 먹...",
      "x": "127.04640850052863",
      "y": "37.54551923341322",
      "map_url": "https://map.kakao.com/link/search/%EC%BD%94%EB%A6%AC%EC%95%BC",
      "kakao_url": "https://place.map.kakao.com/917278025",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 2,
      "menu": [
        "코리야"
      ]
    },
    {
      "name": "크레페보이",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 통인동 102",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] - 두바이크레페\n• [영상 2: 경복궁역 두바이 크레페] - 두바이 크레페",
      "x": "126.97077342775106",
      "y": "37.58037527946966",
      "map_url": "https://map.kakao.com/link/search/%ED%81%AC%EB%A0%88%ED%8E%98%EB%B3%B4%EC%9D%B4",
      "kakao_url": "https://place.map.kakao.com/1774099622",
      "youtube_url": "https://www.youtube.com/shorts/-SahFIs2ptU",
      "youtube_title": "하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!",
      "video_count": 2,
      "menu": [
        "두바이크레페",
        "두바이 크레페"
      ]
    },
    {
      "name": "티노마드",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 포은로 112 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 교토가 아니라 서울 카페라고요..?] → 교토 우지 차를 기반으로 정갈한 티타임을 즐길 수 있는 망원동의 예약제 카페 <티노마드>. 번잡한 워크인 없이 차분하고 여유롭게 시간을 보낼 수...\n• [영상 2: 서울 말차 빙수 모음집]",
      "x": "126.90468348466128",
      "y": "37.55695778553113",
      "map_url": "https://map.kakao.com/link/search/%ED%8B%B0%EB%85%B8%EB%A7%88%EB%93%9C",
      "kakao_url": "https://place.map.kakao.com/731433223",
      "youtube_url": "https://www.youtube.com/shorts/ODxEQHQwvW8",
      "youtube_title": "교토가 아니라 서울 카페라고요..?",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "파티세리아모니",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 656-609",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 디저트에 미친 사람의 2025년은 어땠을까..?] - 단호박 타르트\n• [영상 2: 미슐랭 투스타 출신 쉐프가 만든 타르트]",
      "x": "127.04705948629486",
      "y": "37.55143673479033",
      "map_url": "https://map.kakao.com/link/search/%ED%8C%8C%ED%8B%B0%EC%84%B8%EB%A6%AC%EC%95%84%EB%AA%A8%EB%8B%88",
      "kakao_url": "https://place.map.kakao.com/655580798",
      "youtube_url": "https://www.youtube.com/shorts/4EUphEtgyWI",
      "youtube_title": "디저트에 미친 사람의 2025년은 어땠을까..?",
      "video_count": 2,
      "menu": [
        "단호박 타르트"
      ]
    },
    {
      "name": "팽페르뒤",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 260-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 억지 유행이라는 우베 디저트 근황] - 우베 코코넛 프렌치토스트\n• [영상 2: 이걸로 이제 프렌치토스트까지 만든다고..?] - 팽페르뒤",
      "x": "126.9249822208778",
      "y": "37.561913494105895",
      "map_url": "https://map.kakao.com/link/search/%ED%8C%BD%ED%8E%98%EB%A5%B4%EB%92%A4",
      "kakao_url": "https://place.map.kakao.com/1095923524",
      "youtube_url": "https://www.youtube.com/shorts/0Frib43pNNk",
      "youtube_title": "억지 유행이라는 우베 디저트 근황",
      "video_count": 2,
      "menu": [
        "우베 코코넛 프렌치토스트",
        "팽페르뒤"
      ]
    },
    {
      "name": "포시즌스 호텔 서울",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 당주동 30",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 말차 빙수 모음집]\n• [영상 2: 국밥 10그릇 가격 말차 빙수] - 제주 애플망고 빙수",
      "x": "126.97540468501765",
      "y": "37.570681633888455",
      "map_url": "https://map.kakao.com/link/search/%ED%8F%AC%EC%8B%9C%EC%A6%8C%EC%8A%A4%20%ED%98%B8%ED%85%94%20%EC%84%9C%EC%9A%B8",
      "kakao_url": "https://place.map.kakao.com/22959013",
      "youtube_url": "https://www.youtube.com/shorts/mh-ixVr8MGU",
      "youtube_title": "서울 말차 빙수 모음집",
      "video_count": 2,
      "menu": [
        "제주 애플망고 빙수"
      ]
    },
    {
      "name": "포포민즈낫띵 방배점",
      "category": "☕카페",
      "location_large": "서울 서초구",
      "road_address": "서울 서초구 방배로23길 18 101호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울 파티세리 모음집]\n• [영상 2: 최고의 피스타치오 디저트]",
      "x": "126.99322943158901",
      "y": "37.48628536420314",
      "map_url": "https://map.kakao.com/link/search/%ED%8F%AC%ED%8F%AC%EB%AF%BC%EC%A6%88%EB%82%AB%EB%9D%B5%20%EB%B0%A9%EB%B0%B0%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1717680253",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 2,
      "menu": []
    },
    {
      "name": "피에트라",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 375-116",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "🍰 투데이디저트 2회 추천 디저트 핫플!\n• [영상 1: 서울에서 파는 레몬젤라또]\n• [영상 2: 디저트에 미친 사람의 2025년은 어땠을까..?] - 레몬젤라또",
      "x": "126.92003385971312",
      "y": "37.566144927955825",
      "map_url": "https://map.kakao.com/link/search/%ED%94%BC%EC%97%90%ED%8A%B8%EB%9D%BC",
      "kakao_url": "https://place.map.kakao.com/1088555709",
      "youtube_url": "https://www.youtube.com/shorts/Y30nTqsppI4",
      "youtube_title": "서울에서 파는 레몬젤라또",
      "video_count": 2,
      "menu": [
        "레몬젤라또"
      ]
    },
    {
      "name": "123젤라또 한남점",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 이태원로54길 7 지하1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "한강진역 골목에 위치한 수제 젤라또 전문점 <123젤라또 한남점>. 이곳은 매장에서 반죽을 직접 구워 만드는 수제 콘을 선보이는데, 다양한 콘 토핑을 취향껏 고를 수 있는 게 특징이다. 이번에 맛본 블루베리 젤라또는 우유 풍미가 베이스에 크림치즈 맛이 전체적으로 강하게 치고 올라온다. 치즈케이크도 아낌없이 들어가 있어 진하고 묵직하게 맛있다. 젤라또 자체도 완성도가 높은 편이지만, 매장에서 갓 구워낸 바삭한 콘의 존재감이 훨씬 독보적이다. 솔직히 이 수제 콘의 식감과 맛이 자꾸 생각나서 콘만 먹으러 다시 오고 싶어질 정도!",
      "x": "127.00192348262341",
      "y": "37.53737248729996",
      "map_url": "https://map.kakao.com/link/search/123%EC%A0%A4%EB%9D%BC%EB%98%90%20%ED%95%9C%EB%82%A8%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1043936002",
      "youtube_url": "https://www.youtube.com/shorts/0nDW_9BBw10",
      "youtube_title": "젤라또집인데 젤라또보다 다른게 더 맛있네요..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "5TO7",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 서울숲2길 44-13 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[펄 크림브륄레 수플레] 투데이디저트 추천 핫플레이스",
      "x": "127.04332186706203",
      "y": "37.54608262957489",
      "map_url": "https://map.kakao.com/link/search/5TO7",
      "kakao_url": "https://place.map.kakao.com/328817208",
      "youtube_url": "https://www.youtube.com/shorts/TaatQiiBQcI",
      "youtube_title": "펄 크림브륄레 수플레",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "과자방",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 큰우물로 16 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "마포구 대흥동에 위치한 구움과자 전문점 <과자방>. 이곳에서 시즌 한정으로 선보이는 '찰나의 살구'라는 메뉴를 맛보았다. 부드러운 제누아즈 위를 고소한 피스타치오 무슬린 크림, 상큼한 살구로 빈틈없이 채우고 살구 줄레와 샹티 크림을 짜서 마무리한 디저트. 새콤달콤한 살구의 맛과 묵직하고 고소한 피스타치오 크림의 조화가 무척 매력적이다. 손이 엄청 많이 가는 까다로운 과정을 거치는 만큼 전체적인 디저트의 완성도가 상당하다. 이름 그대로 찰나의 순간에만 맛볼 수 있는 귀한 메뉴이니, 살구 시즌이 끝나기 전에 꼭 한번 들러보시길..! [추천 디저트: 찰나의 살구]",
      "x": "126.94102275041801",
      "y": "37.5444035938752",
      "map_url": "https://map.kakao.com/link/search/%EA%B3%BC%EC%9E%90%EB%B0%A9",
      "kakao_url": "https://place.map.kakao.com/1351616757",
      "youtube_url": "https://www.youtube.com/shorts/ZI0181PG2oU",
      "youtube_title": "지금 놓치면 1년을 기다려야하는 케이크",
      "video_count": 1,
      "menu": [
        "찰나의 살구"
      ]
    },
    {
      "name": "남영역찹쌀잉어빵",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 청파동3가 12-4",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[이건 붕어빵이 아닙니다..] 투데이디저트 추천 핫플레이스",
      "x": "126.97096491478906",
      "y": "37.542046925683536",
      "map_url": "https://map.kakao.com/link/search/%EB%82%A8%EC%98%81%EC%97%AD%EC%B0%B9%EC%8C%80%EC%9E%89%EC%96%B4%EB%B9%B5",
      "kakao_url": "https://place.map.kakao.com/163135012",
      "youtube_url": "https://www.youtube.com/shorts/49Zd2JizJTc",
      "youtube_title": "이건 붕어빵이 아닙니다..",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "네즈",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 망원동 57-108",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 초당옥수수 디저트 모음집] 초당옥수수파르페 [추천 디저트: 초당옥수수파르페]",
      "x": "126.91156227637715",
      "y": "37.55889127183529",
      "map_url": "https://map.kakao.com/link/search/%EB%84%A4%EC%A6%88",
      "kakao_url": "https://place.map.kakao.com/140453980",
      "youtube_url": "https://www.youtube.com/shorts/6uZPP5HVDLw",
      "youtube_title": "서울 초당옥수수 디저트 모음집",
      "video_count": 1,
      "menu": [
        "초당옥수수파르페"
      ]
    },
    {
      "name": "넬리슨",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 삼일대로32길 45 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "종로에 위치한 수제 초콜릿 전문점 <넬리슨>. 벨기에 출신 사장님이 선보이는 '멜로케이크'가 시그니처 메뉴이다. 24시간 휴지해 구운 아몬드 쿠키에 초콜릿을 코팅해 바삭함을 살리고, 해풍 쑥을 아낌없이 넣은 쑥 마시멜로 크림을 올린 뒤 겉면을 쑥 초콜릿으로 코팅해 디저트를 완성한다. 진하고 향긋한 쑥 본연의 풍미가 입안에 묵직하게 퍼진다. 바삭한 쿠키와 부드러운 마시멜로의 식감 대비가 좋으며, 단맛이 꽤 있는 편이라 깔끔한 아메리카노나 드립 커피와 함께 곁들이는 걸 추천! [추천 디저트: 멜로케이크]",
      "x": "126.98946751226497",
      "y": "37.57561036639454",
      "map_url": "https://map.kakao.com/link/search/%EB%84%AC%EB%A6%AC%EC%8A%A8",
      "kakao_url": "https://place.map.kakao.com/1135045200",
      "youtube_url": "https://www.youtube.com/shorts/d0pKbRh3TaQ",
      "youtube_title": "쑥 마시멜로가 가득 올라간 쿠키..?",
      "video_count": 1,
      "menu": [
        "멜로케이크"
      ]
    },
    {
      "name": "노버든",
      "category": "☕카페",
      "location_large": "서울 영등포구",
      "road_address": "서울 영등포구 당산로31길 25 2층 201호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[말차 국수 치즈케이크] [추천 디저트: 말차 덕후들의 성지] 투데이디저트 추천 핫플레이스",
      "x": "126.89379348240173",
      "y": "37.52681907482979",
      "map_url": "https://map.kakao.com/link/search/%EB%85%B8%EB%B2%84%EB%93%A0",
      "kakao_url": "https://place.map.kakao.com/716801125",
      "youtube_url": "https://www.youtube.com/shorts/lTbmcsypthI",
      "youtube_title": "말차 국수 치즈케이크",
      "video_count": 1,
      "menu": [
        "말차 덕후들의 성지"
      ]
    },
    {
      "name": "녹아",
      "category": "☕카페",
      "location_large": "경북 경주시",
      "road_address": "경북 경주시 황남동 239-9",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[4단계 말차빙수 도전..?] [추천 디저트: 녹아(NOKA)] 투데이디저트 추천 핫플레이스",
      "x": "129.2117724576431",
      "y": "35.83607353150583",
      "map_url": "https://map.kakao.com/link/search/%EB%85%B9%EC%95%84",
      "kakao_url": "https://place.map.kakao.com/598623218",
      "youtube_url": "https://www.youtube.com/shorts/ot5zSqGISJY",
      "youtube_title": "4단계 말차빙수 도전..?",
      "video_count": 1,
      "menu": [
        "녹아(NOKA)"
      ]
    },
    {
      "name": "더그랜드롯데 서울",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 을지로 30",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[국내 최고가 딸기 뷔페는 얼마일까..?] 투데이디저트 추천 핫플레이스",
      "x": "126.98100699814147",
      "y": "37.56534516953803",
      "map_url": "https://map.kakao.com/link/search/%EB%8D%94%EA%B7%B8%EB%9E%9C%EB%93%9C%EB%A1%AF%EB%8D%B0%20%EC%84%9C%EC%9A%B8",
      "kakao_url": "https://place.map.kakao.com/7855876",
      "youtube_url": "https://www.youtube.com/shorts/wsdp0rXTy68",
      "youtube_title": "국내 최고가 딸기 뷔페는 얼마일까..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "더그랜드롯데 서울 라세느",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 을지로 30 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[1인 140,000원 국내 최고가 망고 뷔페..?] 투데이디저트 추천 핫플레이스",
      "x": "126.98098436963745",
      "y": "37.56530912605071",
      "map_url": "https://map.kakao.com/link/search/%EB%8D%94%EA%B7%B8%EB%9E%9C%EB%93%9C%EB%A1%AF%EB%8D%B0%20%EC%84%9C%EC%9A%B8%20%EB%9D%BC%EC%84%B8%EB%8A%90",
      "kakao_url": "https://place.map.kakao.com/27348727",
      "youtube_url": "https://www.youtube.com/shorts/VZclE8sA1gw",
      "youtube_title": "1인 140,000원 국내 최고가 망고 뷔페..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "더그랜드롯데 서울 페닌슐라 라운지&바",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 을지로 30 롯데호텔 본관 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 딸기 디저트 모음집] 딸기 뷔페 [추천 디저트: 딸기 뷔페]",
      "x": "126.98066741919699",
      "y": "37.565399174187284",
      "map_url": "https://map.kakao.com/link/search/%EB%8D%94%EA%B7%B8%EB%9E%9C%EB%93%9C%EB%A1%AF%EB%8D%B0%20%EC%84%9C%EC%9A%B8%20%ED%8E%98%EB%8B%8C%EC%8A%90%EB%9D%BC%20%EB%9D%BC%EC%9A%B4%EC%A7%80%26%EB%B0%94",
      "kakao_url": "https://place.map.kakao.com/10356278",
      "youtube_url": "https://www.youtube.com/shorts/2GDztkzQO4A",
      "youtube_title": "2026 딸기 디저트 모음집",
      "video_count": 1,
      "menu": [
        "딸기 뷔페"
      ]
    },
    {
      "name": "독고커피 본점",
      "category": "☕카페",
      "location_large": "경북 경주시",
      "road_address": "경북 경주시 승삼북길 27",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "경주에 위치한 카페 <독고커피>. 요즘 SNS에서 엄청나게 바이럴되고 있는 '얼음 많이 버전 아메리카노'를 주문해 봤다. 말 그대로 잔 위에 산더미만 한 얼음 뭉치를 통째로 올려주는데, 압도적인 비주얼 덕분에 등장하자마자 촬영을 안 할 수가 없다. 커피 맛은 일반 아메리카노와 똑같다. 하루에 딱 5잔만 한정 판매한다고 하니, 올여름 경주 여행을 계획하고 있다면 시원하게 커피 한 잔 하러 가보시길..! [추천 디저트: 얼음 많이 버전 아메리카노]",
      "x": "129.23095482733873",
      "y": "35.87821901613765",
      "map_url": "https://map.kakao.com/link/search/%EB%8F%85%EA%B3%A0%EC%BB%A4%ED%94%BC%20%EB%B3%B8%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/12013580",
      "youtube_url": "https://www.youtube.com/shorts/M3fITugfcCk",
      "youtube_title": "커피로 겨울왕국을 만든 사장님",
      "video_count": 1,
      "menu": [
        "얼음 많이 버전 아메리카노"
      ]
    },
    {
      "name": "라메종뒤쇼콜라 롯데백화점본점",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 소공동 롯데백화점 본점 지하 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[초콜릿을 캐비어로 만들었다고..?] 투데이디저트 추천 핫플레이스",
      "x": "126.98147799274325",
      "y": "37.56481545862733",
      "map_url": "https://map.kakao.com/link/search/%EB%9D%BC%EB%A9%94%EC%A2%85%EB%92%A4%EC%87%BC%EC%BD%9C%EB%9D%BC%20%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EB%B3%B8%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/298908155",
      "youtube_url": "https://www.youtube.com/shorts/7qg5kj4zUa4",
      "youtube_title": "초콜릿을 캐비어로 만들었다고..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "라프레플루트 서촌점",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 옥인동 108",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 딸기 디저트 모음집] 말차 딸기케이크 [추천 디저트: 말차 딸기케이크]",
      "x": "126.96796108732448",
      "y": "37.58078900680051",
      "map_url": "https://map.kakao.com/link/search/%EB%9D%BC%ED%94%84%EB%A0%88%ED%94%8C%EB%A3%A8%ED%8A%B8%20%EC%84%9C%EC%B4%8C%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/2081065470",
      "youtube_url": "https://www.youtube.com/shorts/2GDztkzQO4A",
      "youtube_title": "2026 딸기 디저트 모음집",
      "video_count": 1,
      "menu": [
        "말차 딸기케이크"
      ]
    },
    {
      "name": "라프레플루트 서촌점",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 필운대로 53-30 1, 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[올해 첫 번째 딸기케이크..!] 투데이디저트 추천 핫플레이스",
      "x": "126.96796108732448",
      "y": "37.58078900680051",
      "map_url": "https://map.kakao.com/link/search/%EB%9D%BC%ED%94%84%EB%A0%88%ED%94%8C%EB%A3%A8%ED%8A%B8%20%EC%84%9C%EC%B4%8C%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/2081065470",
      "youtube_url": "https://www.youtube.com/shorts/G-YLzLJuHd4",
      "youtube_title": "올해 첫 번째 딸기케이크..!",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "랑꼬뉴",
      "category": "☕카페",
      "location_large": "위치 –",
      "road_address": "위치 – 서울 강남구 도산대로49길 6-8 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[여기가 아이스크림계의 에르메스라던데..] 투데이디저트 추천 핫플레이스",
      "x": "127.03796928673412",
      "y": "37.52346935303161",
      "map_url": "https://map.kakao.com/link/search/%EB%9E%91%EA%BC%AC%EB%89%B4",
      "kakao_url": "https://place.map.kakao.com/52027889",
      "youtube_url": "https://www.youtube.com/shorts/BA9qlTWnKZw",
      "youtube_title": "여기가 아이스크림계의 에르메스라던데..",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "럭키빵집",
      "category": "☕카페",
      "location_large": "경기 고양시",
      "road_address": "경기 고양시 덕양구 호국로777번길 32",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "고양시에 위치한 동네 빵집 <럭키빵집>. 복날 시즌을 맞아 통닭 비주얼을 리얼하게 구현한 '꼬꼬 통닭 소금빵'을 출시했다. 소금빵 반죽을 부위별로 소분해 한 마리의 닭 모양으로 조립한 뒤 오븐에 노릇하게 구워낸 방식. 맛은 속에 버터동굴이 뚫려 있어 특유의 짭짤하고 고소한 버터 풍미가 잘 느껴진다. 무엇보다 빵 자체가 굉장히 쫄깃쫄깃해서 씹는 맛이 좋은 편. 귀여운 비주얼에 소금빵 기본기까지 탄탄해 소금빵 덕후라면 호기심에라도 들러볼 만하다. [추천 디저트: 꼬꼬 통닭 소금빵]",
      "x": "126.83346037529522",
      "y": "37.656275895298776",
      "map_url": "https://map.kakao.com/link/search/%EB%9F%AD%ED%82%A4%EB%B9%B5%EC%A7%91",
      "kakao_url": "https://place.map.kakao.com/1578383885",
      "youtube_url": "https://www.youtube.com/shorts/WJcmAA9mOF4",
      "youtube_title": "빵 덕후들은 복날에도 '빵'을 먹습니다..?",
      "video_count": 1,
      "menu": [
        "꼬꼬 통닭 소금빵"
      ]
    },
    {
      "name": "레브",
      "category": "☕카페",
      "location_large": "경북 경주시",
      "road_address": "경북 경주시 포석로1068번길 15-14 가, 나동",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[빵을 주문했는데 소파가 나왔습니다..?] [추천 디저트: 레브] 투데이디저트 추천 핫플레이스",
      "x": "129.2112875326848",
      "y": "35.83678167063931",
      "map_url": "https://map.kakao.com/link/search/%EB%A0%88%EB%B8%8C",
      "kakao_url": "https://place.map.kakao.com/699830170",
      "youtube_url": "https://www.youtube.com/shorts/lMWA9yeyoQY",
      "youtube_title": "빵을 주문했는데 소파가 나왔습니다..?",
      "video_count": 1,
      "menu": [
        "레브"
      ]
    },
    {
      "name": "레브두",
      "category": "☕카페",
      "location_large": "서울 송파구",
      "road_address": "서울 송파구 백제고분로45길 19 2층 레브두서울",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "'만겹 크루아상'으로 유명한 파티세리 <레브두>. 요즘 유행하는 왁뿌볼 콘셉트를 크로와상으로 재해석한 '뺑오카라멜'을 새롭게 선보인다. 동그란 볼 형태의 크로와상 속에 우유 풍미 가득한 커스터드 베이스의 디플로마 크림을 채우고, 겉면을 카라멜로 단단하게 코팅해 완성한 빵. 맛은 겉을 감싸고 있는 카라멜의 빠삭한 식감이 깨지면서 묘한 쾌감을 준다. 카라멜이 치아에 전혀 달라붙지 않아 깔끔하게 씹히는 것이 특징. 부드럽고 진한 디플로마 크림과 크로와상의 바삭한 결이 어우러져 와그작 부셔 먹는 재미가 확실하다. [추천 디저트: 만겹 크루아상]",
      "x": "127.10931314606144",
      "y": "37.50981251360307",
      "map_url": "https://map.kakao.com/link/search/%EB%A0%88%EB%B8%8C%EB%91%90",
      "kakao_url": "https://place.map.kakao.com/449198920",
      "youtube_url": "https://www.youtube.com/shorts/B4rFE_ZUhls",
      "youtube_title": "왁뿌볼 크루아상",
      "video_count": 1,
      "menu": [
        "만겹 크루아상"
      ]
    },
    {
      "name": "레종데트르",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 자하문로7길 67-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 파티세리 모음집] 카페 레종데트르 (경복궁역)",
      "x": "126.96889420804399",
      "y": "37.58017297662693",
      "map_url": "https://map.kakao.com/link/search/%EB%A0%88%EC%A2%85%EB%8D%B0%ED%8A%B8%EB%A5%B4",
      "kakao_url": "https://place.map.kakao.com/114971922",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "레종데트르 한남",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 이태원로42길 62 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "한남동에 위치한 프렌치 디저트 부티크 <카페 레종데트르 한남>. 오랜 기다림 끝에 시그니처 디저트 '크림브륄레 브레스트'를 다시 선보인다. 빠삭하게 카라멜라이징한 크림브륄레 슈 사이에 크림으로 진한 바닐라 풍미를 채워낸 구성. 중간중간 씹히는 현미 크런치가 확실한 식감의 킥을 더해준다. [추천 디저트: 크림브륄레 브레스트]",
      "x": "127.00146184334658",
      "y": "37.53719589783376",
      "map_url": "https://map.kakao.com/link/search/%EB%A0%88%EC%A2%85%EB%8D%B0%ED%8A%B8%EB%A5%B4%20%ED%95%9C%EB%82%A8",
      "kakao_url": "https://place.map.kakao.com/1623804721",
      "youtube_url": "https://www.youtube.com/shorts/dvVBrtUQ4-g",
      "youtube_title": "브륄레에 바닐라 조합이면 말 다 한거죠..?",
      "video_count": 1,
      "menu": [
        "크림브륄레 브레스트"
      ]
    },
    {
      "name": "롯지",
      "category": "☕카페",
      "location_large": "서울 서대문구",
      "road_address": "서울 서대문구 연희동 170-3",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 말차 빙수 모음집] 투데이디저트 추천 핫플레이스",
      "x": "126.90739553071144",
      "y": "37.56032606800734",
      "map_url": "https://map.kakao.com/link/search/%EB%A1%AF%EC%A7%80",
      "kakao_url": "https://place.map.kakao.com/2011005664",
      "youtube_url": "https://www.youtube.com/shorts/mh-ixVr8MGU",
      "youtube_title": "서울 말차 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "마이페이보릿쿠키테리아",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 압구정로14길 15",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "압구정 신사동에 위치한 디저트 카페 <마이페이보릿쿠키테리아>. 시즌 한정으로 '무화과 얼그레이 가나슈 모찌'를 선보인다. 직접 치대어 만든 쫄깃한 떡피 속에 진한 얼그레이 가나슈와 생무화과를 통으로 감싼 구성. 뒤로 갈수록 가나슈 특유의 묵직한 단맛이 올라오는 편이라 아메리카노와 함께 곁들여 먹는 걸 추천! [추천 디저트: 무화과 얼그레이 가나슈 모찌]",
      "x": "127.02330824778512",
      "y": "37.523357827999725",
      "map_url": "https://map.kakao.com/link/search/%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EB%B3%B4%EB%A6%BF%EC%BF%A0%ED%82%A4%ED%85%8C%EB%A6%AC%EC%95%84",
      "kakao_url": "https://place.map.kakao.com/1571769694",
      "youtube_url": "https://www.youtube.com/shorts/8HWNIYu32Zs",
      "youtube_title": "건치 인증 가능한 과일모찌",
      "video_count": 1,
      "menu": [
        "무화과 얼그레이 가나슈 모찌"
      ]
    },
    {
      "name": "모찌방",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 삼성로75길 41 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[말차파르페 진짜 잘하는 집] 투데이디저트 추천 핫플레이스",
      "x": "127.05490910802833",
      "y": "37.50250894260411",
      "map_url": "https://map.kakao.com/link/search/%EB%AA%A8%EC%B0%8C%EB%B0%A9",
      "kakao_url": "https://place.map.kakao.com/269779063",
      "youtube_url": "https://www.youtube.com/shorts/irNySfDb5AI",
      "youtube_title": "말차파르페 진짜 잘하는 집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "문식빵",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연남동 255-17",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 식빵 근황.. 이것도 두바이네..?] 투데이디저트 추천 핫플레이스",
      "x": "126.92388598942217",
      "y": "37.56252186604936",
      "map_url": "https://map.kakao.com/link/search/%EB%AC%B8%EC%8B%9D%EB%B9%B5",
      "kakao_url": "https://place.map.kakao.com/1614982616",
      "youtube_url": "https://www.youtube.com/shorts/MEbbGf5wGnk",
      "youtube_title": "2026 식빵 근황.. 이것도 두바이네..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "미미제과점",
      "category": "☕카페",
      "location_large": "대전 서구",
      "road_address": "대전 서구 갈마동 859",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[역대급 두바이 초코크림 소금빵] [추천 디저트: 대전] 투데이디저트 추천 핫플레이스",
      "x": "127.37319127241004",
      "y": "36.352479111503236",
      "map_url": "https://map.kakao.com/link/search/%EB%AF%B8%EB%AF%B8%EC%A0%9C%EA%B3%BC%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/535720711",
      "youtube_url": "https://www.youtube.com/shorts/qysrdIzdXd8",
      "youtube_title": "역대급 두바이 초코크림 소금빵",
      "video_count": 1,
      "menu": [
        "대전"
      ]
    },
    {
      "name": "미세스묵",
      "category": "☕카페",
      "location_large": "제주 제주시",
      "road_address": "제주 제주시 동문로4길 7-1 동문시장 11번게이트",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "제주 동문시장에서 묵푸딩으로 유명한 <미세스묵>. 이번에 버블티의 펄 대신 묵을 채 썰어 넣은 이색 음료 '묵크티(묵 밀크티)'를 출시했다. 직접 쒀서 굳힌 도토리묵과 청포묵을 채 썰어 넣고 우유, 흑당시럽, 홍차를 더해 만드는 방식. 어울리지 않을 것 같은 조합이지만, 묵이 버블 역할을 훌륭하게 대체하며 밀크티와 꽤나 잘 어우러진다. 기본 묵크티 외에도 말차, 초코, 딸기 묵크티등 선택지가 다양해 취향대로 즐길 수 있다. 선물용으로 반응이 좋은 묵푸딩도 함께 판매하고 있으니 동문시장 구경할 때 한번 방문해 보시길..! [추천 디저트: 묵크티(묵 밀크티)]",
      "x": "126.52838101651336",
      "y": "33.512362316112416",
      "map_url": "https://map.kakao.com/link/search/%EB%AF%B8%EC%84%B8%EC%8A%A4%EB%AC%B5",
      "kakao_url": "https://place.map.kakao.com/1251316828",
      "youtube_url": "https://www.youtube.com/shorts/mtR7FUZ-_aU",
      "youtube_title": "K-푸딩으로 만든 밀크티..?",
      "video_count": 1,
      "menu": [
        "묵크티(묵 밀크티)"
      ]
    },
    {
      "name": "베이커리카페 CAT&F",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 연무장길 29-9 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[찰옥수수 소금빵] 투데이디저트 추천 핫플레이스",
      "x": "127.05273487091303",
      "y": "37.5434695073529",
      "map_url": "https://map.kakao.com/link/search/%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC%EC%B9%B4%ED%8E%98%20CAT%26F",
      "kakao_url": "https://place.map.kakao.com/963210354",
      "youtube_url": "https://www.youtube.com/shorts/fcBrLBpopP8",
      "youtube_title": "찰옥수수 소금빵",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "베이킷",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 청파로45길 32 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "용산에 위치한 케이크 전문점 <베이킷>. 이번 시즌 메뉴로 '무화과 얼그레이 케이크'를 새롭게 선보인다. 부드러운 제누와즈 시트 사이에 달콤한 무화과 콤피튀르와 얼그레이 샹티크림, 싱싱한 홍무화과를 층마다 빈틈없이 채워 넣은 구성. 무화과 특유의 향긋함과 부드러운 얼그레이 크림의 풍미가 조화롭게 어우러지는 게 확실한 하이라이트다. 너무 묵직하지 않고 산뜻하게 떨어져 끝까지 질리지 않고 먹기 좋다. [추천 디저트: 무화과 얼그레이 케이크]",
      "x": "126.96883653722102",
      "y": "37.544688113593",
      "map_url": "https://map.kakao.com/link/search/%EB%B2%A0%EC%9D%B4%ED%82%B7",
      "kakao_url": "https://place.map.kakao.com/1316420811",
      "youtube_url": "https://www.youtube.com/shorts/F0YWtZa9BxU",
      "youtube_title": "무화과에 누구보다 진심인 케이크",
      "video_count": 1,
      "menu": [
        "무화과 얼그레이 케이크"
      ]
    },
    {
      "name": "보헤미아",
      "category": "☕카페",
      "location_large": "부산 동래구",
      "road_address": "부산 동래구 온천천로453번길 18 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[연기가 피어오르는 빵] [추천 디저트: 굴뚝빵(뜨르들로)] 투데이디저트 추천 핫플레이스",
      "x": "129.10309835567517",
      "y": "35.19209700854742",
      "map_url": "https://map.kakao.com/link/search/%EB%B3%B4%ED%97%A4%EB%AF%B8%EC%95%84",
      "kakao_url": "https://place.map.kakao.com/1962368701",
      "youtube_url": "https://www.youtube.com/shorts/sOZM9G0BRJE",
      "youtube_title": "연기가 피어오르는 빵",
      "video_count": 1,
      "menu": [
        "굴뚝빵(뜨르들로)"
      ]
    },
    {
      "name": "블리스냅",
      "category": "☕카페",
      "location_large": "서울 강서구",
      "road_address": "서울 강서구 마곡동 1540",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[보라색 모찌 테린느] 투데이디저트 추천 핫플레이스",
      "x": "126.8225300575126",
      "y": "37.570972468597326",
      "map_url": "https://map.kakao.com/link/search/%EB%B8%94%EB%A6%AC%EC%8A%A4%EB%83%85",
      "kakao_url": "https://place.map.kakao.com/931117436",
      "youtube_url": "https://www.youtube.com/shorts/6D593htc2HI",
      "youtube_title": "보라색 모찌 테린느",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "비포블루밍",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 동교동 148-9",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[복숭아 디저트 먹고 싶을 때 보면 좋은 영상] 투데이디저트 추천 핫플레이스",
      "x": "126.92506149194257",
      "y": "37.55961059705523",
      "map_url": "https://map.kakao.com/link/search/%EB%B9%84%ED%8F%AC%EB%B8%94%EB%A3%A8%EB%B0%8D",
      "kakao_url": "https://place.map.kakao.com/1794025679",
      "youtube_url": "https://www.youtube.com/shorts/wpFMvZS7C9g",
      "youtube_title": "복숭아 디저트 먹고 싶을 때 보면 좋은 영상",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "뿡어당",
      "category": "☕카페",
      "location_large": "서울 성북구",
      "road_address": "서울 성북구 동선동2가 308",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!] 두바이붕어빵 [추천 디저트: 두바이붕어빵]",
      "x": "127.02053947181305",
      "y": "37.591228670157896",
      "map_url": "https://map.kakao.com/link/search/%EB%BF%A1%EC%96%B4%EB%8B%B9",
      "kakao_url": "https://place.map.kakao.com/441152273",
      "youtube_url": "https://www.youtube.com/shorts/-SahFIs2ptU",
      "youtube_title": "하루에 한 번씩 두바이 얘기하는 친구한테 공유해 주세요..!",
      "video_count": 1,
      "menu": [
        "두바이붕어빵"
      ]
    },
    {
      "name": "뿡어당",
      "category": "☕카페",
      "location_large": "서울 성북구",
      "road_address": "서울 성북구 동선동2가 308",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[이젠 붕어빵도 두바이..?] [추천 디저트: 두바이] 투데이디저트 추천 핫플레이스",
      "x": "127.02053947181305",
      "y": "37.591228670157896",
      "map_url": "https://map.kakao.com/link/search/%EB%BF%A1%EC%96%B4%EB%8B%B9",
      "kakao_url": "https://place.map.kakao.com/441152273",
      "youtube_url": "https://www.youtube.com/shorts/zTPYSf6WLhY",
      "youtube_title": "이젠 붕어빵도 두바이..?",
      "video_count": 1,
      "menu": [
        "두바이"
      ]
    },
    {
      "name": "사월의물고기",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 관훈동 118-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[쑥떡이 올라가는 커피는 맛있을까..?] [추천 디저트: 사월의물고기] 투데이디저트 추천 핫플레이스",
      "x": "126.98384810130467",
      "y": "37.575476384088915",
      "map_url": "https://map.kakao.com/link/search/%EC%82%AC%EC%9B%94%EC%9D%98%EB%AC%BC%EA%B3%A0%EA%B8%B0",
      "kakao_url": "https://place.map.kakao.com/2068926243",
      "youtube_url": "https://www.youtube.com/shorts/dYnnvn4O8Vs",
      "youtube_title": "쑥떡이 올라가는 커피는 맛있을까..?",
      "video_count": 1,
      "menu": [
        "사월의물고기"
      ]
    },
    {
      "name": "서울신라호텔",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 장충동2가 202",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 빙수 모음집] 신라호텔 (동대입구역)",
      "x": "127.00517884800654",
      "y": "37.555954592538384",
      "map_url": "https://map.kakao.com/link/search/%EC%84%9C%EC%9A%B8%EC%8B%A0%EB%9D%BC%ED%98%B8%ED%85%94",
      "kakao_url": "https://place.map.kakao.com/14576878",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "서울신라호텔 더 라이브러리",
      "category": "☕카페",
      "location_large": "<서울 중구",
      "road_address": "<서울 중구 동호로 249>",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[신라호텔 트러플 아이스크림] [추천 디저트: 트러플] 투데이디저트 추천 핫플레이스",
      "x": "127.00517431705443",
      "y": "37.55589692889247",
      "map_url": "https://map.kakao.com/link/search/%EC%84%9C%EC%9A%B8%EC%8B%A0%EB%9D%BC%ED%98%B8%ED%85%94%20%EB%8D%94%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/21548513",
      "youtube_url": "https://www.youtube.com/shorts/RH3lK40S8X8",
      "youtube_title": "신라호텔 트러플 아이스크림",
      "video_count": 1,
      "menu": [
        "트러플"
      ]
    },
    {
      "name": "서울신라호텔 더 라이브러리",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 동호로 249 서울신라호텔 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[내 주식보다 잘 오르는 빙수] 투데이디저트 추천 핫플레이스",
      "x": "127.00517431705443",
      "y": "37.55589692889247",
      "map_url": "https://map.kakao.com/link/search/%EC%84%9C%EC%9A%B8%EC%8B%A0%EB%9D%BC%ED%98%B8%ED%85%94%20%EB%8D%94%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/21548513",
      "youtube_url": "https://www.youtube.com/shorts/TlhukXkr95I",
      "youtube_title": "내 주식보다 잘 오르는 빙수",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "섬광",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 창경궁로1길 38 5층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[치즈케이크가 통으로 올라간 프렌치토스트] 투데이디저트 추천 핫플레이스",
      "x": "126.99632830914481",
      "y": "37.56252111563513",
      "map_url": "https://map.kakao.com/link/search/%EC%84%AC%EA%B4%91",
      "kakao_url": "https://place.map.kakao.com/1039797847",
      "youtube_url": "https://www.youtube.com/shorts/BJTQiG8u-tg",
      "youtube_title": "치즈케이크가 통으로 올라간 프렌치토스트",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "센잇",
      "category": "☕카페",
      "location_large": "제주 제주시",
      "road_address": "제주 제주시 관덕로8길 13",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "제주 동문시장 근처에 위치한 해산물 센베 전문점 <센잇>. 각종 해산물을 1톤 프레스로 얇게 압착해 만드는 이색 화석과자를 선보인다. 새우가 들어간 화석과자는 극강의 바삭함에 고소하고 짭짤한 풍미가 가득해 마치 고급스러운 새우깡을 먹는 느낌이다. 비주얼도 독특하고 부담 없이 즐기기 좋아 한 번쯤 경험해볼 만하다.",
      "x": "126.52354869437929",
      "y": "33.51191827450229",
      "map_url": "https://map.kakao.com/link/search/%EC%84%BC%EC%9E%87",
      "kakao_url": "https://place.map.kakao.com/277053265",
      "youtube_url": "https://www.youtube.com/shorts/w557mwwjLtU",
      "youtube_title": "1톤으로 눌러 만든 화석과자",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "수르기",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 한남동 683-65",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[올해 크리스마스 케이크는 너다] 투데이디저트 추천 핫플레이스",
      "x": "127.04614141539811",
      "y": "37.47196852141856",
      "map_url": "https://map.kakao.com/link/search/%EC%88%98%EB%A5%B4%EA%B8%B0",
      "kakao_url": "https://place.map.kakao.com/382988755",
      "youtube_url": "https://www.youtube.com/shorts/Oj34Dqh7g-U",
      "youtube_title": "올해 크리스마스 케이크는 너다",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "아뜰리에커피앤밀크티 대림점",
      "category": "☕카페",
      "location_large": "서울 영등포구",
      "road_address": "서울 영등포구 대림동 1057-21",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "대림역 인근에 위치한 <아뜰리에 커피 앤 밀크티>. 이곳은 얇게 밀어내는 일반적인 롤 형태가 아니라, 네모난 큐브 모양으로 두툼하고 단단하게 얼려주는 철판 아이스크림을 선보인다. 생용과를 넣어 만든 '용과 큐브 아이스크림'은 딱 용과랑 요거트를 합쳐서 얼린 직관적인 맛. 두께감 있게 각을 잡아 얼려내는 만큼 쉽게 녹지 않고 묵직한 식감을 유지하는 게 특징이다. [추천 디저트: 용과 큐브 아이스크림]",
      "x": "126.89755571250234",
      "y": "37.49240763870003",
      "map_url": "https://map.kakao.com/link/search/%EC%95%84%EB%9C%B0%EB%A6%AC%EC%97%90%EC%BB%A4%ED%94%BC%EC%95%A4%EB%B0%80%ED%81%AC%ED%8B%B0%20%EB%8C%80%EB%A6%BC%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/258547837",
      "youtube_url": "https://www.youtube.com/shorts/KLw-TEjMEhU",
      "youtube_title": "네모네모빔 맞은 철판 아이스크림",
      "video_count": 1,
      "menu": [
        "용과 큐브 아이스크림"
      ]
    },
    {
      "name": "아임도넛 성수점",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 연무장길 37-30 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[요즘 MZ들은 성수동 가면 어딜 갈까?] 일본에서 줄 서서 먹던 부드럽고 쫄깃한 식감의 도넛, 이제 성수동에서도 만날 수 있다. 기존 도넛과는 다른 촉촉한 반죽과 밀도감 있는 탄력이 가장 큰 특징이며, 한 입만으로도 식감의 차이를 확실히 느낄 수 있다.",
      "x": "127.05393445624117",
      "y": "37.54366358140795",
      "map_url": "https://map.kakao.com/link/search/%EC%95%84%EC%9E%84%EB%8F%84%EB%84%9B%20%EC%84%B1%EC%88%98%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/2139543219",
      "youtube_url": "https://www.youtube.com/shorts/3WbPOgfOvrA",
      "youtube_title": "요즘 MZ들은 성수동 가면 어딜 갈까?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "앰배서더 서울 풀만",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 장충동2가 186-54",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 빙수 모음집] 앰버서더 서울 풀만 (동대입구역)",
      "x": "127.0023315165826",
      "y": "37.56011368639862",
      "map_url": "https://map.kakao.com/link/search/%EC%95%B0%EB%B0%B0%EC%84%9C%EB%8D%94%20%EC%84%9C%EC%9A%B8%20%ED%92%80%EB%A7%8C",
      "kakao_url": "https://place.map.kakao.com/2049779313",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "앰배서더 서울 풀만",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 동호로 287",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[1+1 5성급 호텔 카이막 빙수] 투데이디저트 추천 핫플레이스",
      "x": "127.0023315165826",
      "y": "37.56011368639862",
      "map_url": "https://map.kakao.com/link/search/%EC%95%B0%EB%B0%B0%EC%84%9C%EB%8D%94%20%EC%84%9C%EC%9A%B8%20%ED%92%80%EB%A7%8C",
      "kakao_url": "https://place.map.kakao.com/2049779313",
      "youtube_url": "https://www.youtube.com/shorts/6vGyy0iX7pE",
      "youtube_title": "1+1 5성급 호텔 카이막 빙수",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "어퍼앤언더",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 역삼동 618-17",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 초당옥수수 디저트 모음집] 초당옥수수 파이 [추천 디저트: 초당옥수수 파이]",
      "x": "127.02772606381411",
      "y": "37.50273829563315",
      "map_url": "https://map.kakao.com/link/search/%EC%96%B4%ED%8D%BC%EC%95%A4%EC%96%B8%EB%8D%94",
      "kakao_url": "https://place.map.kakao.com/1116018239",
      "youtube_url": "https://www.youtube.com/shorts/6uZPP5HVDLw",
      "youtube_title": "서울 초당옥수수 디저트 모음집",
      "video_count": 1,
      "menu": [
        "초당옥수수 파이"
      ]
    },
    {
      "name": "연희동국화빵",
      "category": "☕카페",
      "location_large": "서울 서대문구",
      "road_address": "서울 서대문구 연희동 189-4",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[호지차 슈크림 국화빵] 투데이디저트 추천 핫플레이스",
      "x": "126.92880784601165",
      "y": "37.56663347855034",
      "map_url": "https://map.kakao.com/link/search/%EC%97%B0%ED%9D%AC%EB%8F%99%EA%B5%AD%ED%99%94%EB%B9%B5",
      "kakao_url": "https://place.map.kakao.com/1210768362",
      "youtube_url": "https://www.youtube.com/shorts/VVod1W0r0js",
      "youtube_title": "호지차 슈크림 국화빵",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "예커피",
      "category": "☕카페",
      "location_large": "서울 구로구",
      "road_address": "서울 구로구 개봉동 56-10",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[카이막이 통으로 올라간 말차티라미수] [추천 디저트: 카이막 성지] 투데이디저트 추천 핫플레이스",
      "x": "126.84233543802254",
      "y": "37.501955174384705",
      "map_url": "https://map.kakao.com/link/search/%EC%98%88%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/720651307",
      "youtube_url": "https://www.youtube.com/shorts/LYlEW4qhzTc",
      "youtube_title": "카이막이 통으로 올라간 말차티라미수",
      "video_count": 1,
      "menu": [
        "카이막 성지"
      ]
    },
    {
      "name": "오고르",
      "category": "☕카페",
      "location_large": "경기 수원시",
      "road_address": "경기 수원시 팔달구 장안동 119-6",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[(AI 아님) 두바이초밥 진짜 나왔습니다..!] [추천 디저트: 두바이 초밥] 투데이디저트 추천 핫플레이스",
      "x": "127.01578768722302",
      "y": "37.28640866197243",
      "map_url": "https://map.kakao.com/link/search/%EC%98%A4%EA%B3%A0%EB%A5%B4",
      "kakao_url": "https://place.map.kakao.com/1177481226",
      "youtube_url": "https://www.youtube.com/shorts/gxOgTHYi8BQ",
      "youtube_title": "(AI 아님) 두바이초밥 진짜 나왔습니다..!",
      "video_count": 1,
      "menu": [
        "두바이 초밥"
      ]
    },
    {
      "name": "오븐브라더스 목동본점",
      "category": "☕카페",
      "location_large": "대전 중구",
      "road_address": "대전 중구 목동 98-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[바삭함이 남다른 애플파이] 투데이디저트 추천 핫플레이스",
      "x": "127.40924403686486",
      "y": "36.332351381454814",
      "map_url": "https://map.kakao.com/link/search/%EC%98%A4%EB%B8%90%EB%B8%8C%EB%9D%BC%EB%8D%94%EC%8A%A4%20%EB%AA%A9%EB%8F%99%EB%B3%B8%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1077695230",
      "youtube_url": "https://www.youtube.com/shorts/AKN6ApZ4KG4",
      "youtube_title": "바삭함이 남다른 애플파이",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "우나스",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 삼성동 94-11",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[아보카도로 디저트를 만들면 생기는 일] [추천 디저트: 우나스(UNAS)] 투데이디저트 추천 핫플레이스",
      "x": "127.0627977260317",
      "y": "37.5177824435977",
      "map_url": "https://map.kakao.com/link/search/%EC%9A%B0%EB%82%98%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/1900672501",
      "youtube_url": "https://www.youtube.com/shorts/9LDs2R5cjdM",
      "youtube_title": "아보카도로 디저트를 만들면 생기는 일",
      "video_count": 1,
      "menu": [
        "우나스(UNAS)"
      ]
    },
    {
      "name": "우스블랑 성수",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수이로7가길 19-7",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "빵덕후라면 모를 수가 없는 <우스블랑> 성수동 매장의 시그니처 빵. 바게트 사이에 카라멜 팝콘과 다양한 견과류, 헤이즐넛 크림을 가득 채운 '버터카라멜바게트'를 선보인다. 수제 카라멜 베이스에 펄 솔트, 피칸·캐슈넛 등 다양한 견과류와 팝콘을 버무려 샌드하고, 그 위에 헤이즐넛 크림을 짜 올린 구성. 바삭한 바게트와 팝콘, 고소한 견과류가 어우러지는 식감이 꽤 재미있다. 단짠의 밸런스가 잡힌 카라멜에 진한 헤이즐넛 크림의 케미가 괜찮았다. [추천 디저트: 버터카라멜바게트]",
      "x": "127.05517330717026",
      "y": "37.54185380212318",
      "map_url": "https://map.kakao.com/link/search/%EC%9A%B0%EC%8A%A4%EB%B8%94%EB%9E%91%20%EC%84%B1%EC%88%98",
      "kakao_url": "https://place.map.kakao.com/536223868",
      "youtube_url": "https://www.youtube.com/shorts/nHIZBl1tyno",
      "youtube_title": "카라멜로 샤워한 바게트",
      "video_count": 1,
      "menu": [
        "버터카라멜바게트"
      ]
    },
    {
      "name": "원스타베이커리",
      "category": "☕카페",
      "location_large": "서울 동대문구",
      "road_address": "서울 동대문구 천호대로79길 85 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "장안동 골목에 위치한 베이커리 <원스타베이커리>. 이미 빵덕후들 사이에서는 빵 맛집으로 명성이 자자한 곳이다. 여름을 맞아 새롭게 출시한 메론빵이 있다길래 바로 다녀왔다. 일단 메론빵 겉면의 쿠키 층이 두툼해서 바작바작 씹히는 식감부터 아주 마음에 든다. 반으로 가른 빵 사이에는 진한 우유 풍미의 아이스크림이 꽉 채워져 있고, 그 위에 생메론과 레몬 조각이 올라간다. 레몬즙을 아이스크림 위에 살짝 뿌려 먹는 방식인데, 상큼한 산미가 더해지니 자칫 무거울 수 있는 단맛을 깔끔하게 잡아준다. 가격대는 다소 높은 편이지만, 두툼한 쿠키 층과 속 재료의 밸런스가 훌륭해 메론빵을 좋아하는 사람이라면 한 번쯤 경험해 볼 만하다.",
      "x": "127.06490721162449",
      "y": "37.56591990848685",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%90%EC%8A%A4%ED%83%80%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/1916712707",
      "youtube_url": "https://www.youtube.com/shorts/Yb8ybbYbxgY",
      "youtube_title": "서울에서 단 하나의 메론빵을 먹는다면..",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "원앤온리커피",
      "category": "☕카페",
      "location_large": "서울 서대문구",
      "road_address": "서울 서대문구 대현동 37-7",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 서울 치즈케이크 모음집..!] 무화과 크림치즈케이크 [추천 디저트: 무화과 크림치즈케이크]",
      "x": "126.94379579236409",
      "y": "37.55853620115505",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%90%EC%95%A4%EC%98%A8%EB%A6%AC%EC%BB%A4%ED%94%BC",
      "kakao_url": "https://place.map.kakao.com/560241790",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 1,
      "menu": [
        "무화과 크림치즈케이크"
      ]
    },
    {
      "name": "원어거스트8월1일",
      "category": "☕카페",
      "location_large": "부산 해운대구",
      "road_address": "부산 해운대구 우동 550-6",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[해운대에서 가장 아름다운 파이..?] 투데이디저트 추천 핫플레이스",
      "x": "129.15938233662362",
      "y": "35.16340141280694",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%90%EC%96%B4%EA%B1%B0%EC%8A%A4%ED%8A%B88%EC%9B%941%EC%9D%BC",
      "kakao_url": "https://place.map.kakao.com/995496508",
      "youtube_url": "https://www.youtube.com/shorts/_-1l-wlZnoI",
      "youtube_title": "해운대에서 가장 아름다운 파이..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "웨스틴조선 서울",
      "category": "☕카페",
      "location_large": "서울 중구",
      "road_address": "서울 중구 소공동 87-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 빙수 모음집] 웨스틴 조선 서울 (시청역)",
      "x": "126.98002022984936",
      "y": "37.564469238378855",
      "map_url": "https://map.kakao.com/link/search/%EC%9B%A8%EC%8A%A4%ED%8B%B4%EC%A1%B0%EC%84%A0%20%EC%84%9C%EC%9A%B8",
      "kakao_url": "https://place.map.kakao.com/10686757",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "이너피스베이커리",
      "category": "☕카페",
      "location_large": "서울 서초구",
      "road_address": "서울 서초구 양재천로29길 15 1층 102호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "양재천 근처 베이커리 <이너피스베이커리>에서 새롭게 출시한 '무화과 파블로바'. 무려 생무화과 1kg이 빈틈없이 들어간다. 저온에 구운 머랭 시트 위에 무화과잎과 바닐라를 우려낸 마스카포네 크림, 무화과 콤포트와 생무화과를 꽉 채운 구성. 사르르 녹아내리는 머랭과 향긋한 무화과잎 크림의 조화가 역대급이다. 무화과 덕후라면 시즌 끝나기 전에 꼭 한번 드셔보시길..! [추천 디저트: 무화과 파블로바]",
      "x": "127.04182268424105",
      "y": "37.47950617464479",
      "map_url": "https://map.kakao.com/link/search/%EC%9D%B4%EB%84%88%ED%94%BC%EC%8A%A4%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/1314977707",
      "youtube_url": "https://www.youtube.com/shorts/uCdUSxAqBPI",
      "youtube_title": "무화과 케이크 1등",
      "video_count": 1,
      "menu": [
        "무화과 파블로바"
      ]
    },
    {
      "name": "인터랙트",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 강남대로118길 16 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "신논현역 인근 글루텐프리 디저트 전문점 <인터랙트>. 유제품과 설탕, 밀가루를 배제하고 선보인 신메뉴 '피스타치오 케이크'. 시판 퓨레나 버터 없이 피스타치오 견과류와 캐슈넛을 통째로 갈아 넣어 원물 본연의 고소함을 가득 채워낸 구성. 진하게 느껴지는 피스타치오 원물 맛이 상큼한 체리와 깔끔하게 어우러진다. - [추천 디저트: 피스타치오 케이크]",
      "x": "127.02489091597093",
      "y": "37.5064835054804",
      "map_url": "https://map.kakao.com/link/search/%EC%9D%B8%ED%84%B0%EB%9E%99%ED%8A%B8",
      "kakao_url": "https://place.map.kakao.com/332630576",
      "youtube_url": "https://www.youtube.com/shorts/mtL3mLUfL3E",
      "youtube_title": "당뇨 걸린 사장님 본인이 먹고 싶어서 만든 케이크..?",
      "video_count": 1,
      "menu": [
        "피스타치오 케이크"
      ]
    },
    {
      "name": "재인",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 이태원로54길 48 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 파티세리 모음집] 재인 (한강진역)",
      "x": "127.00126721810756",
      "y": "37.53633814760389",
      "map_url": "https://map.kakao.com/link/search/%EC%9E%AC%EC%9D%B8",
      "kakao_url": "https://place.map.kakao.com/1934747490",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "재인",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 이태원로54길 48 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[케이크 위에 꽃이 핀다면..?] [추천 디저트: 재인] 투데이디저트 추천 핫플레이스",
      "x": "127.00126721810756",
      "y": "37.53633814760389",
      "map_url": "https://map.kakao.com/link/search/%EC%9E%AC%EC%9D%B8",
      "kakao_url": "https://place.map.kakao.com/1934747490",
      "youtube_url": "https://www.youtube.com/shorts/-nOOp4Z8avY",
      "youtube_title": "케이크 위에 꽃이 핀다면..?",
      "video_count": 1,
      "menu": [
        "재인"
      ]
    },
    {
      "name": "제이앤쇼토",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 압구정로18길 14-6 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "무려 5년 연속 블루리본에 선정된 케이크 맛집?! ⠀ 생과일 크림케이크로 유명한 <쇼토>. 기교 없이 담백한 맛으로 꾸준히 사랑받는 곳이다. 시즌마다 케이크를 먹어보지만 개인적으로는 애플망고 시즌이 가장 만족스러웠다. ⠀ 부드럽고 촉촉한 시트 사이 담백한 크림과 당도 높은 애플망고가 완벽하게 어우러진다. 본격적으로 망고 시즌이 시작된 지금, 어디에서 첫 망고 디저트를 먹을지 고민 중인 분들께 추천드리고 싶은 곳.",
      "x": "127.02430843056398",
      "y": "37.52384777173811",
      "map_url": "https://map.kakao.com/link/search/%EC%A0%9C%EC%9D%B4%EC%95%A4%EC%87%BC%ED%86%A0",
      "kakao_url": "https://place.map.kakao.com/1745920539",
      "youtube_url": "https://www.youtube.com/shorts/jPH_f9-NAjc",
      "youtube_title": "한 조각에 16500원 애플망고 케이크",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "조선빙고",
      "category": "☕카페",
      "location_large": "서울 영등포구",
      "road_address": "서울 영등포구 여의도동 525",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 빙수 모음집] 조선빙고 (여의나루역)",
      "x": "126.9293368070583",
      "y": "37.524290447584555",
      "map_url": "https://map.kakao.com/link/search/%EC%A1%B0%EC%84%A0%EB%B9%99%EA%B3%A0",
      "kakao_url": "https://place.map.kakao.com/1481137456",
      "youtube_url": "https://www.youtube.com/shorts/WrQYKul5cFw",
      "youtube_title": "서울 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "천장지구 서울",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 언주로150길 51 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[3000원짜리 도미빵] [추천 디저트: 도미빵] 투데이디저트 추천 핫플레이스",
      "x": "127.03834872638089",
      "y": "37.52217899474059",
      "map_url": "https://map.kakao.com/link/search/%EC%B2%9C%EC%9E%A5%EC%A7%80%EA%B5%AC%20%EC%84%9C%EC%9A%B8",
      "kakao_url": "https://place.map.kakao.com/954348165",
      "youtube_url": "https://www.youtube.com/shorts/uOOAWbI7EmI",
      "youtube_title": "3000원짜리 도미빵",
      "video_count": 1,
      "menu": [
        "도미빵"
      ]
    },
    {
      "name": "카시코이",
      "category": "☕카페",
      "location_large": "서울 서대문구",
      "road_address": "서울 서대문구 연희동 446-285",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울에서 발견한 수제 당고 맛집..!] 투데이디저트 추천 핫플레이스",
      "x": "126.9185877152074",
      "y": "37.567841415374005",
      "map_url": "https://map.kakao.com/link/search/%EC%B9%B4%EC%8B%9C%EC%BD%94%EC%9D%B4",
      "kakao_url": "https://place.map.kakao.com/425794374",
      "youtube_url": "https://www.youtube.com/shorts/QtUmYxKL3zE",
      "youtube_title": "서울에서 발견한 수제 당고 맛집..!",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "카페제이",
      "category": "☕카페",
      "location_large": "서울 강동구",
      "road_address": "서울 강동구 동남로82길 19",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[국내 최초 블루리본 말차 전문점] 투데이디저트 추천 핫플레이스",
      "x": "127.15800554447806",
      "y": "37.560685531711606",
      "map_url": "https://map.kakao.com/link/search/%EC%B9%B4%ED%8E%98%EC%A0%9C%EC%9D%B4",
      "kakao_url": "https://place.map.kakao.com/1980415186",
      "youtube_url": "https://www.youtube.com/shorts/RefilOtoPaM",
      "youtube_title": "국내 최초 블루리본 말차 전문점",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "커피브론즈",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 율곡로5길 20 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 딸기 디저트 모음집] 4단 딸기케이크 [추천 디저트: 4단 딸기케이크]",
      "x": "126.98485302349211",
      "y": "37.57708749538226",
      "map_url": "https://map.kakao.com/link/search/%EC%BB%A4%ED%94%BC%EB%B8%8C%EB%A1%A0%EC%A6%88",
      "kakao_url": "https://place.map.kakao.com/16874884",
      "youtube_url": "https://www.youtube.com/shorts/2GDztkzQO4A",
      "youtube_title": "2026 딸기 디저트 모음집",
      "video_count": 1,
      "menu": [
        "4단 딸기케이크"
      ]
    },
    {
      "name": "퀸즈베리도넛하우스 방배점",
      "category": "☕카페",
      "location_large": "서울 서초구",
      "road_address": "서울 서초구 방배로19길 63 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[강민경님이 픽한 도넛 가게] 투데이디저트 추천 핫플레이스",
      "x": "126.99184118364484",
      "y": "37.484090420058656",
      "map_url": "https://map.kakao.com/link/search/%ED%80%B8%EC%A6%88%EB%B2%A0%EB%A6%AC%EB%8F%84%EB%84%9B%ED%95%98%EC%9A%B0%EC%8A%A4%20%EB%B0%A9%EB%B0%B0%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/150584439",
      "youtube_url": "https://www.youtube.com/shorts/8QMieV6ouvE",
      "youtube_title": "강민경님이 픽한 도넛 가게",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "크레뮤클럽",
      "category": "☕카페",
      "location_large": "서울 송파구",
      "road_address": "서울 송파구 백제고분로45길 21 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "시즌마다 다양한 디저트를 선보이는 <크레뮤클럽>에서 재출시한 '무화과 프렌치토스트'와 '말차 무화과 판나코타'. 하루 동안 앙글레이즈에 재워 구워낸 브리오슈 프토는 속까지 촉촉한 식감이 살아있다. 매장에서 만든 꾸덕한 그릭 리코타 크림, 상큼한 크랜베리 콤포트, 바삭한 그래놀라와 생무화과가 더해져 밸런스를 잡아준다. 우지산 말차 판나코타에 아쌈 몽떼크림을 올린 디저트도 쌉싸름함과 부드러움의 합이 좋은 편. 다양한 버전으로 무화과를 경험하고 싶다면 한번 방문해 보시길..! [추천 디저트: 무화과 프렌치토스트]",
      "x": "127.10915484214166",
      "y": "37.50984149212985",
      "map_url": "https://map.kakao.com/link/search/%ED%81%AC%EB%A0%88%EB%AE%A4%ED%81%B4%EB%9F%BD",
      "kakao_url": "https://place.map.kakao.com/81791583",
      "youtube_url": "https://www.youtube.com/shorts/vPtPFRsP8ns",
      "youtube_title": "무화과 프렌치토스트",
      "video_count": 1,
      "menu": [
        "무화과 프렌치토스트"
      ]
    },
    {
      "name": "크림라벨 마포도화점",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 도화동 251-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[억지 유행이라는 우베 디저트 근황] 우베 딸기케이크 [추천 디저트: 우베 딸기케이크]",
      "x": "126.94709662191363",
      "y": "37.538531953320586",
      "map_url": "https://map.kakao.com/link/search/%ED%81%AC%EB%A6%BC%EB%9D%BC%EB%B2%A8%20%EB%A7%88%ED%8F%AC%EB%8F%84%ED%99%94%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/397658999",
      "youtube_url": "https://www.youtube.com/shorts/0Frib43pNNk",
      "youtube_title": "억지 유행이라는 우베 디저트 근황",
      "video_count": 1,
      "menu": [
        "우베 딸기케이크"
      ]
    },
    {
      "name": "키튼커피하우스",
      "category": "☕카페",
      "location_large": "부산 부산진구",
      "road_address": "부산 부산진구 전포동 653-13",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[강아지 케이크] 투데이디저트 추천 핫플레이스",
      "x": "129.06425564296032",
      "y": "35.15878110284643",
      "map_url": "https://map.kakao.com/link/search/%ED%82%A4%ED%8A%BC%EC%BB%A4%ED%94%BC%ED%95%98%EC%9A%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/591768245",
      "youtube_url": "https://www.youtube.com/shorts/Lwbv5lcJLqk",
      "youtube_title": "강아지 케이크",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "타르데마 베이커리 마곡나루",
      "category": "☕카페",
      "location_large": "곡나루역보타닉비즈타워 1층",
      "road_address": "곡나루역보타닉비즈타워 1층 105호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "마곡나루역 인근 베이커리 <타르데마 베이커리>. 쿠키슈와 찰빵을 접목해 선보인 신메뉴 '쿠키슈 찰팥빵'을 맛보고 왔다. 바삭한 크럼블을 올린 쫄깃한 찰빵 속에 수제 우유팥크림을 가득 채워낸 구성. 쿠키슈 특유의 바삭함과 찰빵의 쫀득함이 부드러운 우유팥크림과 조화롭게 어우러진다. [추천 디저트: 쿠키슈 찰팥빵]",
      "x": "126.82654251450221",
      "y": "37.56868990653389",
      "map_url": "https://map.kakao.com/link/search/%ED%83%80%EB%A5%B4%EB%8D%B0%EB%A7%88%20%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC%20%EB%A7%88%EA%B3%A1%EB%82%98%EB%A3%A8",
      "kakao_url": "https://place.map.kakao.com/1837180389",
      "youtube_url": "https://www.youtube.com/shorts/DLzLIAn_kf0",
      "youtube_title": "이런 팥빵을 제가 또 먹을 수 있을까요..?",
      "video_count": 1,
      "menu": [
        "쿠키슈 찰팥빵"
      ]
    },
    {
      "name": "토스티데이즈",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 신흥로 97-6 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[프렌치토스트 덕후들의 숨겨진 아지트] 투데이디저트 추천 핫플레이스",
      "x": "128.5766343130651",
      "y": "38.20088887781082",
      "map_url": "https://map.kakao.com/link/search/%ED%86%A0%EC%8A%A4%ED%8B%B0%EB%8D%B0%EC%9D%B4%EC%A6%88",
      "kakao_url": "https://place.map.kakao.com/611527289",
      "youtube_url": "https://www.youtube.com/shorts/94S3qguO6BI",
      "youtube_title": "프렌치토스트 덕후들의 숨겨진 아지트",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "톨쌀롱",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 성미산로 128 2층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "연남동 수제 떡 전문점 <톨쌀롱>. 일반적인 송편의 틀을 깬 독창적인 비주얼로 선보인 이번 추석 시즌 '송편 세트'. 해산물과 과일, 버섯 모양으로 정교하게 빚어낸 떡 속에 밤, 깨, 흑임자 소를 채운 구성. 떡 피의 쫄깃한 식감이 확실하고 고소한 소와의 조화가 깔끔하다. 68,000원으로 가격대는 다소 높은 편이지만, 먹어본 송편 중 가장 특별했던..! [추천 디저트: 송편 세트]",
      "x": "126.92097442988972",
      "y": "37.56296324330795",
      "map_url": "https://map.kakao.com/link/search/%ED%86%A8%EC%8C%80%EB%A1%B1",
      "kakao_url": "https://place.map.kakao.com/671421361",
      "youtube_url": "https://www.youtube.com/shorts/9VKEpL5qHOI",
      "youtube_title": "이번 추석에 이런 송편 사가면..",
      "video_count": 1,
      "menu": [
        "송편 세트"
      ]
    },
    {
      "name": "트키 도산",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 신사동 651-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[2026 서울 치즈케이크 모음집..!] 흑임자 바스크 치즈케이크 [추천 디저트: 흑임자 바스크 치즈케이크]",
      "x": "127.03597359363472",
      "y": "37.523120388772504",
      "map_url": "https://map.kakao.com/link/search/%ED%8A%B8%ED%82%A4%20%EB%8F%84%EC%82%B0",
      "kakao_url": "https://place.map.kakao.com/1611616845",
      "youtube_url": "https://www.youtube.com/shorts/6NP7TexFHfo",
      "youtube_title": "2026 서울 치즈케이크 모음집..!",
      "video_count": 1,
      "menu": [
        "흑임자 바스크 치즈케이크"
      ]
    },
    {
      "name": "티에이알티",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 한강대로52길 29-8 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 파티세리 모음집] 티에이알티 (삼각지역)",
      "x": "126.97301898737636",
      "y": "37.53167149154187",
      "map_url": "https://map.kakao.com/link/search/%ED%8B%B0%EC%97%90%EC%9D%B4%EC%95%8C%ED%8B%B0",
      "kakao_url": "https://place.map.kakao.com/757834218",
      "youtube_url": "https://www.youtube.com/shorts/O7J-uI-WvMM",
      "youtube_title": "서울 파티세리 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "티에이알티",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 한강대로52길 29-8 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[이건 타르트가 아니라 '예술'입니다..!] [추천 디저트: ART)>\n📍주소 - 서울 용산구 한강대로52길 29-8 1층\n\n용산 삼각지 근처에 위치한 프리미엄 파티세리 ] 투데이디저트 추천 핫플레이스",
      "x": "126.97301898737636",
      "y": "37.53167149154187",
      "map_url": "https://map.kakao.com/link/search/%ED%8B%B0%EC%97%90%EC%9D%B4%EC%95%8C%ED%8B%B0",
      "kakao_url": "https://place.map.kakao.com/757834218",
      "youtube_url": "https://www.youtube.com/shorts/j13TjMzDeew",
      "youtube_title": "이건 타르트가 아니라 '예술'입니다..!",
      "video_count": 1,
      "menu": [
        "ART)>\n📍주소 - 서울 용산구 한강대로52길 29-8 1층\n\n용산 삼각지 근처에 위치한 프리미엄 파티세리"
      ]
    },
    {
      "name": "파란시",
      "category": "☕카페",
      "location_large": "전남 여수시",
      "road_address": "전남 여수시 돌산읍 진모1길 29-42",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[빵에 진심인 대형 카페] 투데이디저트 추천 핫플레이스",
      "x": "127.75682834776558",
      "y": "34.70647335411488",
      "map_url": "https://map.kakao.com/link/search/%ED%8C%8C%EB%9E%80%EC%8B%9C",
      "kakao_url": "https://place.map.kakao.com/1831295554",
      "youtube_url": "https://www.youtube.com/shorts/lowGvdQmXIw",
      "youtube_title": "빵에 진심인 대형 카페",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "푸드떼",
      "category": "☕카페",
      "location_large": "서울 종로구",
      "road_address": "서울 종로구 사간동 26",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[복숭아 크림브륄레 파르페] [추천 디저트: 복숭아 크렘브륄레 파르페] 투데이디저트 추천 핫플레이스",
      "x": "126.98136605296132",
      "y": "37.57798078276651",
      "map_url": "https://map.kakao.com/link/search/%ED%91%B8%EB%93%9C%EB%96%BC",
      "kakao_url": "https://place.map.kakao.com/763707742",
      "youtube_url": "https://www.youtube.com/shorts/ADSYX0Wvync",
      "youtube_title": "복숭아 크림브륄레 파르페",
      "video_count": 1,
      "menu": [
        "복숭아 크렘브륄레 파르페"
      ]
    },
    {
      "name": "피킹플레져",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 왕십리로14길 19-7 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[요즘 MZ들은 성수동 가면 어딜 갈까?] 개성 있는 먹방으로 큰 사랑을 받고 있는 유튜버 박뚜기님의 소금빵 브랜드. 버터 향 가득한 오리지널 소금빵은 1,900원부터 시작해 합리적인 가격대가 매력적이다. 겉은 바삭하고 속은 쫄깃한 식감이라 기본만으로도 충분히 만족스러웠다.",
      "x": "127.0459941372544",
      "y": "37.54887111119338",
      "map_url": "https://map.kakao.com/link/search/%ED%94%BC%ED%82%B9%ED%94%8C%EB%A0%88%EC%A0%B8",
      "kakao_url": "https://place.map.kakao.com/985392413",
      "youtube_url": "https://www.youtube.com/shorts/3WbPOgfOvrA",
      "youtube_title": "요즘 MZ들은 성수동 가면 어딜 갈까?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "피킹플레져",
      "category": "☕카페",
      "location_large": "서울 성동구",
      "road_address": "서울 성동구 성수동1가 7-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[38만 유튜버의 명란소금빵!?] 투데이디저트 추천 핫플레이스",
      "x": "127.0459941372544",
      "y": "37.54887111119338",
      "map_url": "https://map.kakao.com/link/search/%ED%94%BC%ED%82%B9%ED%94%8C%EB%A0%88%EC%A0%B8",
      "kakao_url": "https://place.map.kakao.com/985392413",
      "youtube_url": "https://www.youtube.com/shorts/sk-r6YqHWno",
      "youtube_title": "38만 유튜버의 명란소금빵!?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "하루노유키",
      "category": "☕카페",
      "location_large": "서울 강동구",
      "road_address": "서울 강동구 성내동 444-2",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[교토가 아니라 서울이라고요..?] [추천 디저트: 하루노유키] 투데이디저트 추천 핫플레이스",
      "x": "127.13171488712477",
      "y": "37.52413722855419",
      "map_url": "https://map.kakao.com/link/search/%ED%95%98%EB%A3%A8%EB%85%B8%EC%9C%A0%ED%82%A4",
      "kakao_url": "https://place.map.kakao.com/497980490",
      "youtube_url": "https://www.youtube.com/shorts/knAFjgTN-wI",
      "youtube_title": "교토가 아니라 서울이라고요..?",
      "video_count": 1,
      "menu": [
        "하루노유키"
      ]
    },
    {
      "name": "하우스오브버터",
      "category": "☕카페",
      "location_large": "서울 광진구",
      "road_address": "서울 광진구 능동로 343 1층",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "요즘 인스타그램 알고리즘에 계속 뜨길래 다녀온 화제의 디저트집. 고구마맛탕을 휘낭시에로 재해석한 색다른 디저트를 맛보고 왔다. 오븐에서 1시간 이상 천천히 익혀 단맛을 끌어올린 꿀고구마를 반죽 위에 큼직하게 얹어 구워낸 구성. 고메버터의 깊은 풍미와 겉면의 빠작한 코팅 식감, 그리고 속의 촉촉함이 조화롭게 어우러져 만족스러웠던..!",
      "x": "127.08088330955462",
      "y": "37.560172500136446",
      "map_url": "https://map.kakao.com/link/search/%ED%95%98%EC%9A%B0%EC%8A%A4%EC%98%A4%EB%B8%8C%EB%B2%84%ED%84%B0",
      "kakao_url": "https://place.map.kakao.com/881449657",
      "youtube_url": "https://www.youtube.com/shorts/-QPEO6oo-54",
      "youtube_title": "이게 바로 왁뿌 휘낭시에인가요..?",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "하트온케이크 연남점",
      "category": "☕카페",
      "location_large": "서울 마포구",
      "road_address": "서울 마포구 연희로1길 7 1층 102호",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[친구 생일에 선물해주고 싶은 케이크 1위..?] [추천 디저트: 하트온케이크 연남점] 투데이디저트 추천 핫플레이스",
      "x": "126.92607561641003",
      "y": "37.559575196498706",
      "map_url": "https://map.kakao.com/link/search/%ED%95%98%ED%8A%B8%EC%98%A8%EC%BC%80%EC%9D%B4%ED%81%AC%20%EC%97%B0%EB%82%A8%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/1979951853",
      "youtube_url": "https://www.youtube.com/shorts/9eA_cBram4U",
      "youtube_title": "친구 생일에 선물해주고 싶은 케이크 1위..?",
      "video_count": 1,
      "menu": [
        "하트온케이크 연남점"
      ]
    },
    {
      "name": "하티하티하우스",
      "category": "☕카페",
      "location_large": "안국동 114-1",
      "road_address": "안국동 114-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[안국역 에그타르트 비밀 아지트] 투데이디저트 추천 핫플레이스",
      "x": "126.98462207415672",
      "y": "37.57713071325055",
      "map_url": "https://map.kakao.com/link/search/%ED%95%98%ED%8B%B0%ED%95%98%ED%8B%B0%ED%95%98%EC%9A%B0%EC%8A%A4",
      "kakao_url": "https://place.map.kakao.com/1432460444",
      "youtube_url": "https://www.youtube.com/shorts/Yf1TOixFWos",
      "youtube_title": "안국역 에그타르트 비밀 아지트",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "헤브어트리",
      "category": "☕카페",
      "location_large": "서울 용산구",
      "road_address": "서울 용산구 갈월동 59-8",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 초당옥수수 디저트 모음집] 옥수수푸딩(초당x) [추천 디저트: 옥수수푸딩(초당x)]",
      "x": "126.97281489928822",
      "y": "37.545352231922294",
      "map_url": "https://map.kakao.com/link/search/%ED%97%A4%EB%B8%8C%EC%96%B4%ED%8A%B8%EB%A6%AC",
      "kakao_url": "https://place.map.kakao.com/2015614593",
      "youtube_url": "https://www.youtube.com/shorts/6uZPP5HVDLw",
      "youtube_title": "서울 초당옥수수 디저트 모음집",
      "video_count": 1,
      "menu": [
        "옥수수푸딩(초당x)"
      ]
    },
    {
      "name": "홍팥집 양재점",
      "category": "☕카페",
      "location_large": "서울 강남구",
      "road_address": "서울 강남구 도곡동 950-5",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[서울 말차 빙수 모음집] 투데이디저트 추천 핫플레이스",
      "x": "127.03563504695802",
      "y": "37.486788352772734",
      "map_url": "https://map.kakao.com/link/search/%ED%99%8D%ED%8C%A5%EC%A7%91%20%EC%96%91%EC%9E%AC%EC%A0%90",
      "kakao_url": "https://place.map.kakao.com/401140368",
      "youtube_url": "https://www.youtube.com/shorts/mh-ixVr8MGU",
      "youtube_title": "서울 말차 빙수 모음집",
      "video_count": 1,
      "menu": []
    },
    {
      "name": "황실댄스스포츠학원",
      "category": "☕카페",
      "location_large": "대전 중구",
      "road_address": "대전 중구 선화동 27-1",
      "rate": "🥄🥄🥄🥄🥄",
      "comment": "[이 추억의 빵을 기억하시나요..?] 투데이디저트 추천 핫플레이스",
      "x": "127.42315369996382",
      "y": "36.32920650181296",
      "map_url": "https://map.kakao.com/link/search/%ED%99%A9%EC%8B%A4%EB%8C%84%EC%8A%A4%EC%8A%A4%ED%8F%AC%EC%B8%A0%ED%95%99%EC%9B%90",
      "kakao_url": "https://place.map.kakao.com/11319311",
      "youtube_url": "https://www.youtube.com/shorts/dhUFzZ8PQ9k",
      "youtube_title": "이 추억의 빵을 기억하시나요..?",
      "video_count": 1,
      "menu": []
    }
  ]
};

if (typeof window !== 'undefined') {
  window.TODAY_DESSERT_FRIEND_DATA = TODAY_DESSERT_FRIEND_DATA;
}
